// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pois_api.proto

package pois_rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestMinerInitParam struct {
	MinerId              []byte   `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestMinerInitParam) Reset()         { *m = RequestMinerInitParam{} }
func (m *RequestMinerInitParam) String() string { return proto.CompactTextString(m) }
func (*RequestMinerInitParam) ProtoMessage()    {}
func (*RequestMinerInitParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{0}
}

func (m *RequestMinerInitParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMinerInitParam.Unmarshal(m, b)
}
func (m *RequestMinerInitParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMinerInitParam.Marshal(b, m, deterministic)
}
func (m *RequestMinerInitParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMinerInitParam.Merge(m, src)
}
func (m *RequestMinerInitParam) XXX_Size() int {
	return xxx_messageInfo_RequestMinerInitParam.Size(m)
}
func (m *RequestMinerInitParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMinerInitParam.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMinerInitParam proto.InternalMessageInfo

func (m *RequestMinerInitParam) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

type ResponseMinerInitParam struct {
	Acc                  []byte   `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`
	KeyN                 []byte   `protobuf:"bytes,2,opt,name=key_n,json=keyN,proto3" json:"key_n,omitempty"`
	KeyG                 []byte   `protobuf:"bytes,3,opt,name=key_g,json=keyG,proto3" json:"key_g,omitempty"`
	Front                int64    `protobuf:"varint,4,opt,name=front,proto3" json:"front,omitempty"`
	Rear                 int64    `protobuf:"varint,5,opt,name=rear,proto3" json:"rear,omitempty"`
	MinerId              []byte   `protobuf:"bytes,6,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	Signature            []byte   `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseMinerInitParam) Reset()         { *m = ResponseMinerInitParam{} }
func (m *ResponseMinerInitParam) String() string { return proto.CompactTextString(m) }
func (*ResponseMinerInitParam) ProtoMessage()    {}
func (*ResponseMinerInitParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{1}
}

func (m *ResponseMinerInitParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMinerInitParam.Unmarshal(m, b)
}
func (m *ResponseMinerInitParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMinerInitParam.Marshal(b, m, deterministic)
}
func (m *ResponseMinerInitParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMinerInitParam.Merge(m, src)
}
func (m *ResponseMinerInitParam) XXX_Size() int {
	return xxx_messageInfo_ResponseMinerInitParam.Size(m)
}
func (m *ResponseMinerInitParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMinerInitParam.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMinerInitParam proto.InternalMessageInfo

func (m *ResponseMinerInitParam) GetAcc() []byte {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *ResponseMinerInitParam) GetKeyN() []byte {
	if m != nil {
		return m.KeyN
	}
	return nil
}

func (m *ResponseMinerInitParam) GetKeyG() []byte {
	if m != nil {
		return m.KeyG
	}
	return nil
}

func (m *ResponseMinerInitParam) GetFront() int64 {
	if m != nil {
		return m.Front
	}
	return 0
}

func (m *ResponseMinerInitParam) GetRear() int64 {
	if m != nil {
		return m.Rear
	}
	return 0
}

func (m *ResponseMinerInitParam) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *ResponseMinerInitParam) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type RequestMinerCommitGenChall struct {
	MinerId              []byte         `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	Commit               *Commits       `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	PoisInfo             *MinerPoisInfo `protobuf:"bytes,3,opt,name=pois_info,json=poisInfo,proto3" json:"pois_info,omitempty"`
	MinerSign            []byte         `protobuf:"bytes,4,opt,name=miner_sign,json=minerSign,proto3" json:"miner_sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RequestMinerCommitGenChall) Reset()         { *m = RequestMinerCommitGenChall{} }
func (m *RequestMinerCommitGenChall) String() string { return proto.CompactTextString(m) }
func (*RequestMinerCommitGenChall) ProtoMessage()    {}
func (*RequestMinerCommitGenChall) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{2}
}

func (m *RequestMinerCommitGenChall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMinerCommitGenChall.Unmarshal(m, b)
}
func (m *RequestMinerCommitGenChall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMinerCommitGenChall.Marshal(b, m, deterministic)
}
func (m *RequestMinerCommitGenChall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMinerCommitGenChall.Merge(m, src)
}
func (m *RequestMinerCommitGenChall) XXX_Size() int {
	return xxx_messageInfo_RequestMinerCommitGenChall.Size(m)
}
func (m *RequestMinerCommitGenChall) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMinerCommitGenChall.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMinerCommitGenChall proto.InternalMessageInfo

func (m *RequestMinerCommitGenChall) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *RequestMinerCommitGenChall) GetCommit() *Commits {
	if m != nil {
		return m.Commit
	}
	return nil
}

func (m *RequestMinerCommitGenChall) GetPoisInfo() *MinerPoisInfo {
	if m != nil {
		return m.PoisInfo
	}
	return nil
}

func (m *RequestMinerCommitGenChall) GetMinerSign() []byte {
	if m != nil {
		return m.MinerSign
	}
	return nil
}

type Commits struct {
	FileIndexs           []int64  `protobuf:"varint,1,rep,packed,name=file_indexs,json=fileIndexs,proto3" json:"file_indexs,omitempty"`
	Roots                [][]byte `protobuf:"bytes,2,rep,name=roots,proto3" json:"roots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commits) Reset()         { *m = Commits{} }
func (m *Commits) String() string { return proto.CompactTextString(m) }
func (*Commits) ProtoMessage()    {}
func (*Commits) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{3}
}

func (m *Commits) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commits.Unmarshal(m, b)
}
func (m *Commits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commits.Marshal(b, m, deterministic)
}
func (m *Commits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commits.Merge(m, src)
}
func (m *Commits) XXX_Size() int {
	return xxx_messageInfo_Commits.Size(m)
}
func (m *Commits) XXX_DiscardUnknown() {
	xxx_messageInfo_Commits.DiscardUnknown(m)
}

var xxx_messageInfo_Commits proto.InternalMessageInfo

func (m *Commits) GetFileIndexs() []int64 {
	if m != nil {
		return m.FileIndexs
	}
	return nil
}

func (m *Commits) GetRoots() [][]byte {
	if m != nil {
		return m.Roots
	}
	return nil
}

type MinerPoisInfo struct {
	Acc                  []byte   `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`
	Front                int64    `protobuf:"varint,2,opt,name=front,proto3" json:"front,omitempty"`
	Rear                 int64    `protobuf:"varint,3,opt,name=rear,proto3" json:"rear,omitempty"`
	KeyN                 []byte   `protobuf:"bytes,4,opt,name=key_n,json=keyN,proto3" json:"key_n,omitempty"`
	KeyG                 []byte   `protobuf:"bytes,5,opt,name=key_g,json=keyG,proto3" json:"key_g,omitempty"`
	StatusTeeSign        []byte   `protobuf:"bytes,6,opt,name=status_tee_sign,json=statusTeeSign,proto3" json:"status_tee_sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinerPoisInfo) Reset()         { *m = MinerPoisInfo{} }
func (m *MinerPoisInfo) String() string { return proto.CompactTextString(m) }
func (*MinerPoisInfo) ProtoMessage()    {}
func (*MinerPoisInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{4}
}

func (m *MinerPoisInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerPoisInfo.Unmarshal(m, b)
}
func (m *MinerPoisInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerPoisInfo.Marshal(b, m, deterministic)
}
func (m *MinerPoisInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerPoisInfo.Merge(m, src)
}
func (m *MinerPoisInfo) XXX_Size() int {
	return xxx_messageInfo_MinerPoisInfo.Size(m)
}
func (m *MinerPoisInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerPoisInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MinerPoisInfo proto.InternalMessageInfo

func (m *MinerPoisInfo) GetAcc() []byte {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *MinerPoisInfo) GetFront() int64 {
	if m != nil {
		return m.Front
	}
	return 0
}

func (m *MinerPoisInfo) GetRear() int64 {
	if m != nil {
		return m.Rear
	}
	return 0
}

func (m *MinerPoisInfo) GetKeyN() []byte {
	if m != nil {
		return m.KeyN
	}
	return nil
}

func (m *MinerPoisInfo) GetKeyG() []byte {
	if m != nil {
		return m.KeyG
	}
	return nil
}

func (m *MinerPoisInfo) GetStatusTeeSign() []byte {
	if m != nil {
		return m.StatusTeeSign
	}
	return nil
}

type Challenge struct {
	Rows                 []*Int64Slice `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	ChallTeeSign         []byte        `protobuf:"bytes,2,opt,name=chall_tee_sign,json=challTeeSign,proto3" json:"chall_tee_sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Challenge) Reset()         { *m = Challenge{} }
func (m *Challenge) String() string { return proto.CompactTextString(m) }
func (*Challenge) ProtoMessage()    {}
func (*Challenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{5}
}

func (m *Challenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Challenge.Unmarshal(m, b)
}
func (m *Challenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Challenge.Marshal(b, m, deterministic)
}
func (m *Challenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Challenge.Merge(m, src)
}
func (m *Challenge) XXX_Size() int {
	return xxx_messageInfo_Challenge.Size(m)
}
func (m *Challenge) XXX_DiscardUnknown() {
	xxx_messageInfo_Challenge.DiscardUnknown(m)
}

var xxx_messageInfo_Challenge proto.InternalMessageInfo

func (m *Challenge) GetRows() []*Int64Slice {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *Challenge) GetChallTeeSign() []byte {
	if m != nil {
		return m.ChallTeeSign
	}
	return nil
}

type Int64Slice struct {
	Values               []int64  `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Slice) Reset()         { *m = Int64Slice{} }
func (m *Int64Slice) String() string { return proto.CompactTextString(m) }
func (*Int64Slice) ProtoMessage()    {}
func (*Int64Slice) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{6}
}

func (m *Int64Slice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Slice.Unmarshal(m, b)
}
func (m *Int64Slice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Slice.Marshal(b, m, deterministic)
}
func (m *Int64Slice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Slice.Merge(m, src)
}
func (m *Int64Slice) XXX_Size() int {
	return xxx_messageInfo_Int64Slice.Size(m)
}
func (m *Int64Slice) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Slice.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Slice proto.InternalMessageInfo

func (m *Int64Slice) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type RequestVerifyCommitAndAccProof struct {
	CommitProofGroup     *CommitProofGroup `protobuf:"bytes,1,opt,name=commit_proof_group,json=commitProofGroup,proto3" json:"commit_proof_group,omitempty"`
	AccProof             *AccProof         `protobuf:"bytes,2,opt,name=acc_proof,json=accProof,proto3" json:"acc_proof,omitempty"`
	MinerId              []byte            `protobuf:"bytes,3,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	MinerSign            []byte            `protobuf:"bytes,4,opt,name=miner_sign,json=minerSign,proto3" json:"miner_sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RequestVerifyCommitAndAccProof) Reset()         { *m = RequestVerifyCommitAndAccProof{} }
func (m *RequestVerifyCommitAndAccProof) String() string { return proto.CompactTextString(m) }
func (*RequestVerifyCommitAndAccProof) ProtoMessage()    {}
func (*RequestVerifyCommitAndAccProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{7}
}

func (m *RequestVerifyCommitAndAccProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVerifyCommitAndAccProof.Unmarshal(m, b)
}
func (m *RequestVerifyCommitAndAccProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVerifyCommitAndAccProof.Marshal(b, m, deterministic)
}
func (m *RequestVerifyCommitAndAccProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVerifyCommitAndAccProof.Merge(m, src)
}
func (m *RequestVerifyCommitAndAccProof) XXX_Size() int {
	return xxx_messageInfo_RequestVerifyCommitAndAccProof.Size(m)
}
func (m *RequestVerifyCommitAndAccProof) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVerifyCommitAndAccProof.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVerifyCommitAndAccProof proto.InternalMessageInfo

func (m *RequestVerifyCommitAndAccProof) GetCommitProofGroup() *CommitProofGroup {
	if m != nil {
		return m.CommitProofGroup
	}
	return nil
}

func (m *RequestVerifyCommitAndAccProof) GetAccProof() *AccProof {
	if m != nil {
		return m.AccProof
	}
	return nil
}

func (m *RequestVerifyCommitAndAccProof) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *RequestVerifyCommitAndAccProof) GetMinerSign() []byte {
	if m != nil {
		return m.MinerSign
	}
	return nil
}

type CommitProofGroup struct {
	CommitProofGroupInner []*CommitProofGroupInner `protobuf:"bytes,1,rep,name=commit_proof_group_inner,json=commitProofGroupInner,proto3" json:"commit_proof_group_inner,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                 `json:"-"`
	XXX_unrecognized      []byte                   `json:"-"`
	XXX_sizecache         int32                    `json:"-"`
}

func (m *CommitProofGroup) Reset()         { *m = CommitProofGroup{} }
func (m *CommitProofGroup) String() string { return proto.CompactTextString(m) }
func (*CommitProofGroup) ProtoMessage()    {}
func (*CommitProofGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{8}
}

func (m *CommitProofGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitProofGroup.Unmarshal(m, b)
}
func (m *CommitProofGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitProofGroup.Marshal(b, m, deterministic)
}
func (m *CommitProofGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitProofGroup.Merge(m, src)
}
func (m *CommitProofGroup) XXX_Size() int {
	return xxx_messageInfo_CommitProofGroup.Size(m)
}
func (m *CommitProofGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitProofGroup.DiscardUnknown(m)
}

var xxx_messageInfo_CommitProofGroup proto.InternalMessageInfo

func (m *CommitProofGroup) GetCommitProofGroupInner() []*CommitProofGroupInner {
	if m != nil {
		return m.CommitProofGroupInner
	}
	return nil
}

type CommitProofGroupInner struct {
	CommitProof          []*CommitProof `protobuf:"bytes,1,rep,name=commit_proof,json=commitProof,proto3" json:"commit_proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommitProofGroupInner) Reset()         { *m = CommitProofGroupInner{} }
func (m *CommitProofGroupInner) String() string { return proto.CompactTextString(m) }
func (*CommitProofGroupInner) ProtoMessage()    {}
func (*CommitProofGroupInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{9}
}

func (m *CommitProofGroupInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitProofGroupInner.Unmarshal(m, b)
}
func (m *CommitProofGroupInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitProofGroupInner.Marshal(b, m, deterministic)
}
func (m *CommitProofGroupInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitProofGroupInner.Merge(m, src)
}
func (m *CommitProofGroupInner) XXX_Size() int {
	return xxx_messageInfo_CommitProofGroupInner.Size(m)
}
func (m *CommitProofGroupInner) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitProofGroupInner.DiscardUnknown(m)
}

var xxx_messageInfo_CommitProofGroupInner proto.InternalMessageInfo

func (m *CommitProofGroupInner) GetCommitProof() []*CommitProof {
	if m != nil {
		return m.CommitProof
	}
	return nil
}

type CommitProof struct {
	Node                 *MhtProof   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Parents              []*MhtProof `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	Elders               []*MhtProof `protobuf:"bytes,3,rep,name=elders,proto3" json:"elders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CommitProof) Reset()         { *m = CommitProof{} }
func (m *CommitProof) String() string { return proto.CompactTextString(m) }
func (*CommitProof) ProtoMessage()    {}
func (*CommitProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{10}
}

func (m *CommitProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitProof.Unmarshal(m, b)
}
func (m *CommitProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitProof.Marshal(b, m, deterministic)
}
func (m *CommitProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitProof.Merge(m, src)
}
func (m *CommitProof) XXX_Size() int {
	return xxx_messageInfo_CommitProof.Size(m)
}
func (m *CommitProof) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitProof.DiscardUnknown(m)
}

var xxx_messageInfo_CommitProof proto.InternalMessageInfo

func (m *CommitProof) GetNode() *MhtProof {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *CommitProof) GetParents() []*MhtProof {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *CommitProof) GetElders() []*MhtProof {
	if m != nil {
		return m.Elders
	}
	return nil
}

type MhtProof struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Label                []byte   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Paths                [][]byte `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	Locs                 []byte   `protobuf:"bytes,4,opt,name=locs,proto3" json:"locs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MhtProof) Reset()         { *m = MhtProof{} }
func (m *MhtProof) String() string { return proto.CompactTextString(m) }
func (*MhtProof) ProtoMessage()    {}
func (*MhtProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{11}
}

func (m *MhtProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MhtProof.Unmarshal(m, b)
}
func (m *MhtProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MhtProof.Marshal(b, m, deterministic)
}
func (m *MhtProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MhtProof.Merge(m, src)
}
func (m *MhtProof) XXX_Size() int {
	return xxx_messageInfo_MhtProof.Size(m)
}
func (m *MhtProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MhtProof.DiscardUnknown(m)
}

var xxx_messageInfo_MhtProof proto.InternalMessageInfo

func (m *MhtProof) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MhtProof) GetLabel() []byte {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *MhtProof) GetPaths() [][]byte {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *MhtProof) GetLocs() []byte {
	if m != nil {
		return m.Locs
	}
	return nil
}

type AccProof struct {
	Indexs               []int64         `protobuf:"varint,1,rep,packed,name=indexs,proto3" json:"indexs,omitempty"`
	Labels               [][]byte        `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	WitChains            *AccWitnessNode `protobuf:"bytes,3,opt,name=wit_chains,json=witChains,proto3" json:"wit_chains,omitempty"`
	AccPath              [][]byte        `protobuf:"bytes,4,rep,name=acc_path,json=accPath,proto3" json:"acc_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AccProof) Reset()         { *m = AccProof{} }
func (m *AccProof) String() string { return proto.CompactTextString(m) }
func (*AccProof) ProtoMessage()    {}
func (*AccProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{12}
}

func (m *AccProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccProof.Unmarshal(m, b)
}
func (m *AccProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccProof.Marshal(b, m, deterministic)
}
func (m *AccProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccProof.Merge(m, src)
}
func (m *AccProof) XXX_Size() int {
	return xxx_messageInfo_AccProof.Size(m)
}
func (m *AccProof) XXX_DiscardUnknown() {
	xxx_messageInfo_AccProof.DiscardUnknown(m)
}

var xxx_messageInfo_AccProof proto.InternalMessageInfo

func (m *AccProof) GetIndexs() []int64 {
	if m != nil {
		return m.Indexs
	}
	return nil
}

func (m *AccProof) GetLabels() [][]byte {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *AccProof) GetWitChains() *AccWitnessNode {
	if m != nil {
		return m.WitChains
	}
	return nil
}

func (m *AccProof) GetAccPath() [][]byte {
	if m != nil {
		return m.AccPath
	}
	return nil
}

type AccWitnessNode struct {
	Elem                 []byte          `protobuf:"bytes,1,opt,name=elem,proto3" json:"elem,omitempty"`
	Wit                  []byte          `protobuf:"bytes,2,opt,name=wit,proto3" json:"wit,omitempty"`
	Acc                  *AccWitnessNode `protobuf:"bytes,3,opt,name=acc,proto3" json:"acc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AccWitnessNode) Reset()         { *m = AccWitnessNode{} }
func (m *AccWitnessNode) String() string { return proto.CompactTextString(m) }
func (*AccWitnessNode) ProtoMessage()    {}
func (*AccWitnessNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{13}
}

func (m *AccWitnessNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccWitnessNode.Unmarshal(m, b)
}
func (m *AccWitnessNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccWitnessNode.Marshal(b, m, deterministic)
}
func (m *AccWitnessNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccWitnessNode.Merge(m, src)
}
func (m *AccWitnessNode) XXX_Size() int {
	return xxx_messageInfo_AccWitnessNode.Size(m)
}
func (m *AccWitnessNode) XXX_DiscardUnknown() {
	xxx_messageInfo_AccWitnessNode.DiscardUnknown(m)
}

var xxx_messageInfo_AccWitnessNode proto.InternalMessageInfo

func (m *AccWitnessNode) GetElem() []byte {
	if m != nil {
		return m.Elem
	}
	return nil
}

func (m *AccWitnessNode) GetWit() []byte {
	if m != nil {
		return m.Wit
	}
	return nil
}

func (m *AccWitnessNode) GetAcc() *AccWitnessNode {
	if m != nil {
		return m.Acc
	}
	return nil
}

type ResponseVerifyCommitOrDeletionProof struct {
	PoisStatus           *PoisStatus `protobuf:"bytes,1,opt,name=pois_status,json=poisStatus,proto3" json:"pois_status,omitempty"`
	SignatureAbove       []byte      `protobuf:"bytes,2,opt,name=signature_above,json=signatureAbove,proto3" json:"signature_above,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResponseVerifyCommitOrDeletionProof) Reset()         { *m = ResponseVerifyCommitOrDeletionProof{} }
func (m *ResponseVerifyCommitOrDeletionProof) String() string { return proto.CompactTextString(m) }
func (*ResponseVerifyCommitOrDeletionProof) ProtoMessage()    {}
func (*ResponseVerifyCommitOrDeletionProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{14}
}

func (m *ResponseVerifyCommitOrDeletionProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseVerifyCommitOrDeletionProof.Unmarshal(m, b)
}
func (m *ResponseVerifyCommitOrDeletionProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseVerifyCommitOrDeletionProof.Marshal(b, m, deterministic)
}
func (m *ResponseVerifyCommitOrDeletionProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseVerifyCommitOrDeletionProof.Merge(m, src)
}
func (m *ResponseVerifyCommitOrDeletionProof) XXX_Size() int {
	return xxx_messageInfo_ResponseVerifyCommitOrDeletionProof.Size(m)
}
func (m *ResponseVerifyCommitOrDeletionProof) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseVerifyCommitOrDeletionProof.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseVerifyCommitOrDeletionProof proto.InternalMessageInfo

func (m *ResponseVerifyCommitOrDeletionProof) GetPoisStatus() *PoisStatus {
	if m != nil {
		return m.PoisStatus
	}
	return nil
}

func (m *ResponseVerifyCommitOrDeletionProof) GetSignatureAbove() []byte {
	if m != nil {
		return m.SignatureAbove
	}
	return nil
}

type PoisStatus struct {
	Acc                  []byte   `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`
	Front                int64    `protobuf:"varint,2,opt,name=front,proto3" json:"front,omitempty"`
	Rear                 int64    `protobuf:"varint,3,opt,name=rear,proto3" json:"rear,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoisStatus) Reset()         { *m = PoisStatus{} }
func (m *PoisStatus) String() string { return proto.CompactTextString(m) }
func (*PoisStatus) ProtoMessage()    {}
func (*PoisStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{15}
}

func (m *PoisStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoisStatus.Unmarshal(m, b)
}
func (m *PoisStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoisStatus.Marshal(b, m, deterministic)
}
func (m *PoisStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoisStatus.Merge(m, src)
}
func (m *PoisStatus) XXX_Size() int {
	return xxx_messageInfo_PoisStatus.Size(m)
}
func (m *PoisStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PoisStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PoisStatus proto.InternalMessageInfo

func (m *PoisStatus) GetAcc() []byte {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *PoisStatus) GetFront() int64 {
	if m != nil {
		return m.Front
	}
	return 0
}

func (m *PoisStatus) GetRear() int64 {
	if m != nil {
		return m.Rear
	}
	return 0
}

type RequestSpaceProofVerify struct {
	SpaceChals                     []int64        `protobuf:"varint,1,rep,packed,name=space_chals,json=spaceChals,proto3" json:"space_chals,omitempty"`
	MinerId                        []byte         `protobuf:"bytes,2,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	PoisInfo                       *MinerPoisInfo `protobuf:"bytes,3,opt,name=pois_info,json=poisInfo,proto3" json:"pois_info,omitempty"`
	Proof                          *SpaceProof    `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	MinerSpaceProofHashPolkadotSig []byte         `protobuf:"bytes,5,opt,name=miner_space_proof_hash_polkadot_sig,json=minerSpaceProofHashPolkadotSig,proto3" json:"miner_space_proof_hash_polkadot_sig,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}       `json:"-"`
	XXX_unrecognized               []byte         `json:"-"`
	XXX_sizecache                  int32          `json:"-"`
}

func (m *RequestSpaceProofVerify) Reset()         { *m = RequestSpaceProofVerify{} }
func (m *RequestSpaceProofVerify) String() string { return proto.CompactTextString(m) }
func (*RequestSpaceProofVerify) ProtoMessage()    {}
func (*RequestSpaceProofVerify) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{16}
}

func (m *RequestSpaceProofVerify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSpaceProofVerify.Unmarshal(m, b)
}
func (m *RequestSpaceProofVerify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSpaceProofVerify.Marshal(b, m, deterministic)
}
func (m *RequestSpaceProofVerify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSpaceProofVerify.Merge(m, src)
}
func (m *RequestSpaceProofVerify) XXX_Size() int {
	return xxx_messageInfo_RequestSpaceProofVerify.Size(m)
}
func (m *RequestSpaceProofVerify) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSpaceProofVerify.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSpaceProofVerify proto.InternalMessageInfo

func (m *RequestSpaceProofVerify) GetSpaceChals() []int64 {
	if m != nil {
		return m.SpaceChals
	}
	return nil
}

func (m *RequestSpaceProofVerify) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *RequestSpaceProofVerify) GetPoisInfo() *MinerPoisInfo {
	if m != nil {
		return m.PoisInfo
	}
	return nil
}

func (m *RequestSpaceProofVerify) GetProof() *SpaceProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *RequestSpaceProofVerify) GetMinerSpaceProofHashPolkadotSig() []byte {
	if m != nil {
		return m.MinerSpaceProofHashPolkadotSig
	}
	return nil
}

type SpaceProof struct {
	Left                 int64             `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	Right                int64             `protobuf:"varint,2,opt,name=right,proto3" json:"right,omitempty"`
	Proofs               []*MhtProofGroup  `protobuf:"bytes,3,rep,name=proofs,proto3" json:"proofs,omitempty"`
	Roots                [][]byte          `protobuf:"bytes,4,rep,name=roots,proto3" json:"roots,omitempty"`
	WitChains            []*AccWitnessNode `protobuf:"bytes,5,rep,name=wit_chains,json=witChains,proto3" json:"wit_chains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SpaceProof) Reset()         { *m = SpaceProof{} }
func (m *SpaceProof) String() string { return proto.CompactTextString(m) }
func (*SpaceProof) ProtoMessage()    {}
func (*SpaceProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{17}
}

func (m *SpaceProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceProof.Unmarshal(m, b)
}
func (m *SpaceProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceProof.Marshal(b, m, deterministic)
}
func (m *SpaceProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceProof.Merge(m, src)
}
func (m *SpaceProof) XXX_Size() int {
	return xxx_messageInfo_SpaceProof.Size(m)
}
func (m *SpaceProof) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceProof.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceProof proto.InternalMessageInfo

func (m *SpaceProof) GetLeft() int64 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *SpaceProof) GetRight() int64 {
	if m != nil {
		return m.Right
	}
	return 0
}

func (m *SpaceProof) GetProofs() []*MhtProofGroup {
	if m != nil {
		return m.Proofs
	}
	return nil
}

func (m *SpaceProof) GetRoots() [][]byte {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *SpaceProof) GetWitChains() []*AccWitnessNode {
	if m != nil {
		return m.WitChains
	}
	return nil
}

type ProofHashAndLeftRight struct {
	SpaceProofHash       []byte   `protobuf:"bytes,1,opt,name=space_proof_hash,json=spaceProofHash,proto3" json:"space_proof_hash,omitempty"`
	Left                 int64    `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`
	Right                int64    `protobuf:"varint,3,opt,name=right,proto3" json:"right,omitempty"`
	TeeId                []byte   `protobuf:"bytes,4,opt,name=tee_id,json=teeId,proto3" json:"tee_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofHashAndLeftRight) Reset()         { *m = ProofHashAndLeftRight{} }
func (m *ProofHashAndLeftRight) String() string { return proto.CompactTextString(m) }
func (*ProofHashAndLeftRight) ProtoMessage()    {}
func (*ProofHashAndLeftRight) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{18}
}

func (m *ProofHashAndLeftRight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofHashAndLeftRight.Unmarshal(m, b)
}
func (m *ProofHashAndLeftRight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofHashAndLeftRight.Marshal(b, m, deterministic)
}
func (m *ProofHashAndLeftRight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofHashAndLeftRight.Merge(m, src)
}
func (m *ProofHashAndLeftRight) XXX_Size() int {
	return xxx_messageInfo_ProofHashAndLeftRight.Size(m)
}
func (m *ProofHashAndLeftRight) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofHashAndLeftRight.DiscardUnknown(m)
}

var xxx_messageInfo_ProofHashAndLeftRight proto.InternalMessageInfo

func (m *ProofHashAndLeftRight) GetSpaceProofHash() []byte {
	if m != nil {
		return m.SpaceProofHash
	}
	return nil
}

func (m *ProofHashAndLeftRight) GetLeft() int64 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *ProofHashAndLeftRight) GetRight() int64 {
	if m != nil {
		return m.Right
	}
	return 0
}

func (m *ProofHashAndLeftRight) GetTeeId() []byte {
	if m != nil {
		return m.TeeId
	}
	return nil
}

type MhtProofGroup struct {
	Proofs               []*MhtProof `protobuf:"bytes,1,rep,name=proofs,proto3" json:"proofs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MhtProofGroup) Reset()         { *m = MhtProofGroup{} }
func (m *MhtProofGroup) String() string { return proto.CompactTextString(m) }
func (*MhtProofGroup) ProtoMessage()    {}
func (*MhtProofGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{19}
}

func (m *MhtProofGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MhtProofGroup.Unmarshal(m, b)
}
func (m *MhtProofGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MhtProofGroup.Marshal(b, m, deterministic)
}
func (m *MhtProofGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MhtProofGroup.Merge(m, src)
}
func (m *MhtProofGroup) XXX_Size() int {
	return xxx_messageInfo_MhtProofGroup.Size(m)
}
func (m *MhtProofGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_MhtProofGroup.DiscardUnknown(m)
}

var xxx_messageInfo_MhtProofGroup proto.InternalMessageInfo

func (m *MhtProofGroup) GetProofs() []*MhtProof {
	if m != nil {
		return m.Proofs
	}
	return nil
}

type ResponseSpaceProofVerify struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSpaceProofVerify) Reset()         { *m = ResponseSpaceProofVerify{} }
func (m *ResponseSpaceProofVerify) String() string { return proto.CompactTextString(m) }
func (*ResponseSpaceProofVerify) ProtoMessage()    {}
func (*ResponseSpaceProofVerify) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{20}
}

func (m *ResponseSpaceProofVerify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSpaceProofVerify.Unmarshal(m, b)
}
func (m *ResponseSpaceProofVerify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSpaceProofVerify.Marshal(b, m, deterministic)
}
func (m *ResponseSpaceProofVerify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSpaceProofVerify.Merge(m, src)
}
func (m *ResponseSpaceProofVerify) XXX_Size() int {
	return xxx_messageInfo_ResponseSpaceProofVerify.Size(m)
}
func (m *ResponseSpaceProofVerify) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSpaceProofVerify.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSpaceProofVerify proto.InternalMessageInfo

func (m *ResponseSpaceProofVerify) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type RequestSpaceProofVerifyTotal struct {
	MinerId              []byte         `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	ProofList            []*BlocksProof `protobuf:"bytes,2,rep,name=proof_list,json=proofList,proto3" json:"proof_list,omitempty"`
	Front                int64          `protobuf:"varint,3,opt,name=front,proto3" json:"front,omitempty"`
	Rear                 int64          `protobuf:"varint,4,opt,name=rear,proto3" json:"rear,omitempty"`
	Acc                  []byte         `protobuf:"bytes,5,opt,name=acc,proto3" json:"acc,omitempty"`
	SpaceChals           []int64        `protobuf:"varint,6,rep,packed,name=space_chals,json=spaceChals,proto3" json:"space_chals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RequestSpaceProofVerifyTotal) Reset()         { *m = RequestSpaceProofVerifyTotal{} }
func (m *RequestSpaceProofVerifyTotal) String() string { return proto.CompactTextString(m) }
func (*RequestSpaceProofVerifyTotal) ProtoMessage()    {}
func (*RequestSpaceProofVerifyTotal) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{21}
}

func (m *RequestSpaceProofVerifyTotal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSpaceProofVerifyTotal.Unmarshal(m, b)
}
func (m *RequestSpaceProofVerifyTotal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSpaceProofVerifyTotal.Marshal(b, m, deterministic)
}
func (m *RequestSpaceProofVerifyTotal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSpaceProofVerifyTotal.Merge(m, src)
}
func (m *RequestSpaceProofVerifyTotal) XXX_Size() int {
	return xxx_messageInfo_RequestSpaceProofVerifyTotal.Size(m)
}
func (m *RequestSpaceProofVerifyTotal) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSpaceProofVerifyTotal.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSpaceProofVerifyTotal proto.InternalMessageInfo

func (m *RequestSpaceProofVerifyTotal) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *RequestSpaceProofVerifyTotal) GetProofList() []*BlocksProof {
	if m != nil {
		return m.ProofList
	}
	return nil
}

func (m *RequestSpaceProofVerifyTotal) GetFront() int64 {
	if m != nil {
		return m.Front
	}
	return 0
}

func (m *RequestSpaceProofVerifyTotal) GetRear() int64 {
	if m != nil {
		return m.Rear
	}
	return 0
}

func (m *RequestSpaceProofVerifyTotal) GetAcc() []byte {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *RequestSpaceProofVerifyTotal) GetSpaceChals() []int64 {
	if m != nil {
		return m.SpaceChals
	}
	return nil
}

type BlocksProof struct {
	ProofHashAndLeftRight *ProofHashAndLeftRight `protobuf:"bytes,1,opt,name=proof_hash_and_left_right,json=proofHashAndLeftRight,proto3" json:"proof_hash_and_left_right,omitempty"`
	Signature             []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *BlocksProof) Reset()         { *m = BlocksProof{} }
func (m *BlocksProof) String() string { return proto.CompactTextString(m) }
func (*BlocksProof) ProtoMessage()    {}
func (*BlocksProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{22}
}

func (m *BlocksProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksProof.Unmarshal(m, b)
}
func (m *BlocksProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksProof.Marshal(b, m, deterministic)
}
func (m *BlocksProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksProof.Merge(m, src)
}
func (m *BlocksProof) XXX_Size() int {
	return xxx_messageInfo_BlocksProof.Size(m)
}
func (m *BlocksProof) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksProof.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksProof proto.InternalMessageInfo

func (m *BlocksProof) GetProofHashAndLeftRight() *ProofHashAndLeftRight {
	if m != nil {
		return m.ProofHashAndLeftRight
	}
	return nil
}

func (m *BlocksProof) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ResponseSpaceProofVerifyTotalSignatureMember struct {
	MinerId              []byte   `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	TotalProofHash       []byte   `protobuf:"bytes,2,opt,name=total_proof_hash,json=totalProofHash,proto3" json:"total_proof_hash,omitempty"`
	Front                int64    `protobuf:"varint,3,opt,name=front,proto3" json:"front,omitempty"`
	Rear                 int64    `protobuf:"varint,4,opt,name=rear,proto3" json:"rear,omitempty"`
	Acc                  []byte   `protobuf:"bytes,5,opt,name=acc,proto3" json:"acc,omitempty"`
	SpaceChals           []int64  `protobuf:"varint,6,rep,packed,name=space_chals,json=spaceChals,proto3" json:"space_chals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) Reset() {
	*m = ResponseSpaceProofVerifyTotalSignatureMember{}
}
func (m *ResponseSpaceProofVerifyTotalSignatureMember) String() string {
	return proto.CompactTextString(m)
}
func (*ResponseSpaceProofVerifyTotalSignatureMember) ProtoMessage() {}
func (*ResponseSpaceProofVerifyTotalSignatureMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{23}
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember.Unmarshal(m, b)
}
func (m *ResponseSpaceProofVerifyTotalSignatureMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember.Marshal(b, m, deterministic)
}
func (m *ResponseSpaceProofVerifyTotalSignatureMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember.Merge(m, src)
}
func (m *ResponseSpaceProofVerifyTotalSignatureMember) XXX_Size() int {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember.Size(m)
}
func (m *ResponseSpaceProofVerifyTotalSignatureMember) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember proto.InternalMessageInfo

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetTotalProofHash() []byte {
	if m != nil {
		return m.TotalProofHash
	}
	return nil
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetFront() int64 {
	if m != nil {
		return m.Front
	}
	return 0
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetRear() int64 {
	if m != nil {
		return m.Rear
	}
	return 0
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetAcc() []byte {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetSpaceChals() []int64 {
	if m != nil {
		return m.SpaceChals
	}
	return nil
}

type ResponseSpaceProofVerifyTotal struct {
	MinerId              []byte   `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	IdleResult           bool     `protobuf:"varint,2,opt,name=idle_result,json=idleResult,proto3" json:"idle_result,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSpaceProofVerifyTotal) Reset()         { *m = ResponseSpaceProofVerifyTotal{} }
func (m *ResponseSpaceProofVerifyTotal) String() string { return proto.CompactTextString(m) }
func (*ResponseSpaceProofVerifyTotal) ProtoMessage()    {}
func (*ResponseSpaceProofVerifyTotal) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{24}
}

func (m *ResponseSpaceProofVerifyTotal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotal.Unmarshal(m, b)
}
func (m *ResponseSpaceProofVerifyTotal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotal.Marshal(b, m, deterministic)
}
func (m *ResponseSpaceProofVerifyTotal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSpaceProofVerifyTotal.Merge(m, src)
}
func (m *ResponseSpaceProofVerifyTotal) XXX_Size() int {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotal.Size(m)
}
func (m *ResponseSpaceProofVerifyTotal) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSpaceProofVerifyTotal.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSpaceProofVerifyTotal proto.InternalMessageInfo

func (m *ResponseSpaceProofVerifyTotal) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *ResponseSpaceProofVerifyTotal) GetIdleResult() bool {
	if m != nil {
		return m.IdleResult
	}
	return false
}

func (m *ResponseSpaceProofVerifyTotal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type RequestVerifyDeletionProof struct {
	Roots                [][]byte        `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	WitChain             *AccWitnessNode `protobuf:"bytes,2,opt,name=wit_chain,json=witChain,proto3" json:"wit_chain,omitempty"`
	AccPath              [][]byte        `protobuf:"bytes,3,rep,name=acc_path,json=accPath,proto3" json:"acc_path,omitempty"`
	MinerId              []byte          `protobuf:"bytes,4,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	PoisInfo             *MinerPoisInfo  `protobuf:"bytes,5,opt,name=pois_info,json=poisInfo,proto3" json:"pois_info,omitempty"`
	MinerSign            []byte          `protobuf:"bytes,6,opt,name=miner_sign,json=minerSign,proto3" json:"miner_sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RequestVerifyDeletionProof) Reset()         { *m = RequestVerifyDeletionProof{} }
func (m *RequestVerifyDeletionProof) String() string { return proto.CompactTextString(m) }
func (*RequestVerifyDeletionProof) ProtoMessage()    {}
func (*RequestVerifyDeletionProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{25}
}

func (m *RequestVerifyDeletionProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVerifyDeletionProof.Unmarshal(m, b)
}
func (m *RequestVerifyDeletionProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVerifyDeletionProof.Marshal(b, m, deterministic)
}
func (m *RequestVerifyDeletionProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVerifyDeletionProof.Merge(m, src)
}
func (m *RequestVerifyDeletionProof) XXX_Size() int {
	return xxx_messageInfo_RequestVerifyDeletionProof.Size(m)
}
func (m *RequestVerifyDeletionProof) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVerifyDeletionProof.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVerifyDeletionProof proto.InternalMessageInfo

func (m *RequestVerifyDeletionProof) GetRoots() [][]byte {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *RequestVerifyDeletionProof) GetWitChain() *AccWitnessNode {
	if m != nil {
		return m.WitChain
	}
	return nil
}

func (m *RequestVerifyDeletionProof) GetAccPath() [][]byte {
	if m != nil {
		return m.AccPath
	}
	return nil
}

func (m *RequestVerifyDeletionProof) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *RequestVerifyDeletionProof) GetPoisInfo() *MinerPoisInfo {
	if m != nil {
		return m.PoisInfo
	}
	return nil
}

func (m *RequestVerifyDeletionProof) GetMinerSign() []byte {
	if m != nil {
		return m.MinerSign
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestMinerInitParam)(nil), "pois.api.RequestMinerInitParam")
	proto.RegisterType((*ResponseMinerInitParam)(nil), "pois.api.ResponseMinerInitParam")
	proto.RegisterType((*RequestMinerCommitGenChall)(nil), "pois.api.RequestMinerCommitGenChall")
	proto.RegisterType((*Commits)(nil), "pois.api.Commits")
	proto.RegisterType((*MinerPoisInfo)(nil), "pois.api.MinerPoisInfo")
	proto.RegisterType((*Challenge)(nil), "pois.api.Challenge")
	proto.RegisterType((*Int64Slice)(nil), "pois.api.Int64Slice")
	proto.RegisterType((*RequestVerifyCommitAndAccProof)(nil), "pois.api.RequestVerifyCommitAndAccProof")
	proto.RegisterType((*CommitProofGroup)(nil), "pois.api.CommitProofGroup")
	proto.RegisterType((*CommitProofGroupInner)(nil), "pois.api.CommitProofGroupInner")
	proto.RegisterType((*CommitProof)(nil), "pois.api.CommitProof")
	proto.RegisterType((*MhtProof)(nil), "pois.api.MhtProof")
	proto.RegisterType((*AccProof)(nil), "pois.api.AccProof")
	proto.RegisterType((*AccWitnessNode)(nil), "pois.api.AccWitnessNode")
	proto.RegisterType((*ResponseVerifyCommitOrDeletionProof)(nil), "pois.api.ResponseVerifyCommitOrDeletionProof")
	proto.RegisterType((*PoisStatus)(nil), "pois.api.PoisStatus")
	proto.RegisterType((*RequestSpaceProofVerify)(nil), "pois.api.RequestSpaceProofVerify")
	proto.RegisterType((*SpaceProof)(nil), "pois.api.SpaceProof")
	proto.RegisterType((*ProofHashAndLeftRight)(nil), "pois.api.ProofHashAndLeftRight")
	proto.RegisterType((*MhtProofGroup)(nil), "pois.api.MhtProofGroup")
	proto.RegisterType((*ResponseSpaceProofVerify)(nil), "pois.api.ResponseSpaceProofVerify")
	proto.RegisterType((*RequestSpaceProofVerifyTotal)(nil), "pois.api.RequestSpaceProofVerifyTotal")
	proto.RegisterType((*BlocksProof)(nil), "pois.api.BlocksProof")
	proto.RegisterType((*ResponseSpaceProofVerifyTotalSignatureMember)(nil), "pois.api.ResponseSpaceProofVerifyTotalSignatureMember")
	proto.RegisterType((*ResponseSpaceProofVerifyTotal)(nil), "pois.api.ResponseSpaceProofVerifyTotal")
	proto.RegisterType((*RequestVerifyDeletionProof)(nil), "pois.api.RequestVerifyDeletionProof")
}

func init() { proto.RegisterFile("pois_api.proto", fileDescriptor_ea31f2b7d8186a5c) }

var fileDescriptor_ea31f2b7d8186a5c = []byte{
	// 1448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdd, 0x72, 0xdb, 0xc4,
	0x17, 0x8f, 0x22, 0xdb, 0xb1, 0x8f, 0x9d, 0x34, 0xff, 0x6d, 0xdd, 0xaa, 0xfe, 0xf7, 0x23, 0xa8,
	0x99, 0xd6, 0x74, 0x4a, 0x3a, 0x13, 0x5a, 0xe8, 0x0c, 0x37, 0xa4, 0x65, 0xa6, 0xf5, 0xd0, 0x96,
	0xa0, 0x74, 0xf8, 0x1c, 0x46, 0x55, 0xa4, 0xb5, 0xbd, 0x13, 0x45, 0x12, 0xd2, 0x26, 0x69, 0x6e,
	0x19, 0xe0, 0x12, 0x9e, 0x80, 0x0b, 0x5e, 0x02, 0x5e, 0x82, 0x0b, 0x6e, 0x78, 0x13, 0x1e, 0x80,
	0xd9, 0xb3, 0xab, 0x4f, 0xcb, 0x0e, 0x94, 0xe1, 0x6e, 0xf7, 0xe8, 0xec, 0x9e, 0x73, 0x7e, 0xe7,
	0x9c, 0xdf, 0x1e, 0x1b, 0xd6, 0xa2, 0x90, 0x25, 0xb6, 0x13, 0xb1, 0xad, 0x28, 0x0e, 0x79, 0x48,
	0xda, 0x62, 0xbf, 0xe5, 0x44, 0xcc, 0xdc, 0x86, 0xbe, 0x45, 0xbf, 0x3e, 0xa2, 0x09, 0x7f, 0xc6,
	0x02, 0x1a, 0x8f, 0x02, 0xc6, 0x77, 0x9d, 0xd8, 0x39, 0x24, 0x97, 0xa1, 0x7d, 0x28, 0x24, 0x36,
	0xf3, 0x0c, 0x6d, 0x43, 0x1b, 0xf6, 0xac, 0x15, 0xdc, 0x8f, 0x3c, 0xf3, 0x57, 0x0d, 0x2e, 0x5a,
	0x34, 0x89, 0xc2, 0x20, 0xa1, 0x95, 0x53, 0xeb, 0xa0, 0x3b, 0xae, 0xab, 0x0e, 0x88, 0x25, 0x39,
	0x0f, 0xcd, 0x03, 0x7a, 0x6a, 0x07, 0xc6, 0x32, 0xca, 0x1a, 0x07, 0xf4, 0xf4, 0x79, 0x2a, 0x9c,
	0x18, 0x7a, 0x26, 0x7c, 0x4c, 0x2e, 0x40, 0x73, 0x1c, 0x87, 0x01, 0x37, 0x1a, 0x1b, 0xda, 0x50,
	0xb7, 0xe4, 0x86, 0x10, 0x68, 0xc4, 0xd4, 0x89, 0x8d, 0x26, 0x0a, 0x71, 0x5d, 0xf2, 0xad, 0x55,
	0xf2, 0x8d, 0x5c, 0x81, 0x4e, 0xc2, 0x26, 0x81, 0xc3, 0x8f, 0x62, 0x6a, 0xac, 0xe0, 0xb7, 0x5c,
	0x20, 0x3c, 0x1f, 0x14, 0xc3, 0x7d, 0x14, 0x1e, 0x1e, 0x32, 0xfe, 0x98, 0x06, 0x8f, 0xa6, 0x8e,
	0xef, 0x2f, 0x88, 0x99, 0xbc, 0x09, 0x2d, 0x17, 0x95, 0x31, 0x8e, 0xee, 0xf6, 0xff, 0xb6, 0x52,
	0x08, 0xb7, 0xe4, 0x25, 0x89, 0xa5, 0x14, 0xc8, 0x3d, 0xe8, 0x20, 0xdc, 0x2c, 0x18, 0x87, 0x18,
	0x60, 0x77, 0xfb, 0x52, 0xae, 0x8d, 0x76, 0x77, 0x43, 0x96, 0x8c, 0x82, 0x71, 0x68, 0x61, 0x22,
	0xc4, 0x8a, 0x5c, 0x05, 0x90, 0xb6, 0x85, 0xb7, 0x08, 0x41, 0xcf, 0xea, 0xa0, 0x64, 0x8f, 0x4d,
	0x02, 0xf3, 0x7d, 0x58, 0x51, 0x76, 0xc8, 0x75, 0xe8, 0x8e, 0x99, 0x4f, 0x6d, 0x16, 0x78, 0xf4,
	0x55, 0x62, 0x68, 0x1b, 0xfa, 0x50, 0xb7, 0x40, 0x88, 0x46, 0x28, 0x11, 0x40, 0xc6, 0x61, 0xc8,
	0x13, 0x63, 0x79, 0x43, 0x1f, 0xf6, 0x2c, 0xb9, 0x31, 0x7f, 0xd2, 0x60, 0xb5, 0x64, 0xbc, 0x26,
	0x59, 0x59, 0x0a, 0x96, 0xeb, 0x52, 0xa0, 0x17, 0x52, 0x90, 0xa5, 0xb5, 0x51, 0x97, 0xd6, 0x66,
	0x21, 0xad, 0x37, 0xe1, 0x5c, 0xc2, 0x1d, 0x7e, 0x94, 0xd8, 0x9c, 0x52, 0x19, 0x9d, 0xcc, 0xd9,
	0xaa, 0x14, 0xbf, 0xa0, 0x14, 0x23, 0xfc, 0x12, 0x3a, 0x98, 0x05, 0x1a, 0x4c, 0x28, 0x19, 0x42,
	0x23, 0x0e, 0x4f, 0x64, 0x70, 0xdd, 0xed, 0x0b, 0x39, 0x7c, 0xa3, 0x80, 0xbf, 0x73, 0x6f, 0xcf,
	0x67, 0x2e, 0xb5, 0x50, 0x83, 0x6c, 0xc2, 0x9a, 0x2b, 0x8e, 0xe5, 0xb7, 0xcb, 0x42, 0xeb, 0xa1,
	0x34, 0xbd, 0x7c, 0x13, 0x20, 0x3f, 0x49, 0x2e, 0x42, 0xeb, 0xd8, 0xf1, 0x8f, 0x68, 0x0a, 0x9e,
	0xda, 0x99, 0x7f, 0x68, 0x70, 0x4d, 0x95, 0xc7, 0x27, 0x34, 0x66, 0xe3, 0x53, 0x09, 0xf9, 0x4e,
	0xe0, 0xed, 0xb8, 0xee, 0x6e, 0x1c, 0x86, 0x63, 0xf2, 0x04, 0x88, 0x4c, 0xb3, 0x1d, 0x89, 0xbd,
	0x3d, 0x89, 0xc3, 0xa3, 0x08, 0x21, 0xec, 0x6e, 0x0f, 0xaa, 0x35, 0x81, 0x47, 0x1e, 0x0b, 0x0d,
	0x6b, 0xdd, 0xad, 0x48, 0xc8, 0x5d, 0xe8, 0x38, 0xae, 0x2b, 0xaf, 0x51, 0x45, 0x45, 0xf2, 0x0b,
	0x52, 0x83, 0x56, 0xdb, 0x49, 0x4d, 0x17, 0xab, 0x53, 0x2f, 0x57, 0xe7, 0x19, 0xc5, 0xe3, 0xc3,
	0x7a, 0xd5, 0x21, 0xf2, 0x19, 0x18, 0xb3, 0x81, 0xd8, 0x2c, 0x08, 0x68, 0xac, 0x50, 0xbf, 0x3e,
	0x3f, 0x9c, 0x91, 0x50, 0xb3, 0xfa, 0x6e, 0x9d, 0xd8, 0xfc, 0x18, 0xfa, 0xb5, 0xfa, 0xe4, 0x01,
	0xf4, 0x8a, 0x26, 0x95, 0x99, 0x7e, 0xad, 0x19, 0xab, 0x5b, 0xb8, 0xdc, 0xfc, 0x51, 0x83, 0x6e,
	0xe1, 0x23, 0xb9, 0x09, 0x8d, 0x20, 0xf4, 0xa8, 0xc2, 0xbd, 0x00, 0xdb, 0xb3, 0xa9, 0x3a, 0x8e,
	0xdf, 0xc9, 0x1d, 0x58, 0x89, 0x9c, 0x98, 0x06, 0xaa, 0x17, 0xea, 0x55, 0x53, 0x15, 0x72, 0x1b,
	0x5a, 0xd4, 0xf7, 0x68, 0x9c, 0x18, 0xfa, 0x5c, 0x65, 0xa5, 0x61, 0xbe, 0x84, 0x76, 0x2a, 0x13,
	0x5d, 0x83, 0xbd, 0x88, 0xee, 0x34, 0x2d, 0xb9, 0x11, 0x52, 0xdf, 0xd9, 0xa7, 0xbe, 0xaa, 0x47,
	0xb9, 0x11, 0xd2, 0xc8, 0xe1, 0x53, 0x69, 0xa2, 0x67, 0xc9, 0x8d, 0xe8, 0x30, 0x3f, 0x74, 0x93,
	0xb4, 0x99, 0xc4, 0xda, 0xfc, 0x41, 0x83, 0x76, 0x56, 0x76, 0x17, 0xa1, 0x55, 0x6a, 0x77, 0xb5,
	0x13, 0x72, 0xbc, 0x37, 0xed, 0x75, 0xb5, 0x23, 0xef, 0x02, 0x9c, 0x30, 0x6e, 0xbb, 0x53, 0x87,
	0x05, 0x89, 0x22, 0x21, 0xa3, 0x54, 0x5d, 0x9f, 0x32, 0x1e, 0xd0, 0x24, 0x79, 0x1e, 0x7a, 0xd4,
	0xea, 0x9c, 0x30, 0xfe, 0x08, 0x55, 0x45, 0x91, 0x61, 0x55, 0x3a, 0x7c, 0x6a, 0x34, 0xf0, 0xca,
	0x15, 0x51, 0x80, 0x0e, 0x9f, 0x9a, 0xfb, 0xb0, 0x56, 0x3e, 0x27, 0xdc, 0xa6, 0x3e, 0x3d, 0x54,
	0x0c, 0x82, 0x6b, 0x41, 0x2a, 0x27, 0x8a, 0x25, 0x7b, 0x96, 0x58, 0x92, 0xdb, 0x92, 0x66, 0xce,
	0x72, 0x42, 0x28, 0x99, 0xdf, 0x69, 0x70, 0x23, 0x7d, 0x5a, 0x8a, 0x2d, 0xf8, 0x51, 0xfc, 0x01,
	0xf5, 0x29, 0x67, 0x61, 0x20, 0xf1, 0xb8, 0x0f, 0x5d, 0xe4, 0x58, 0x49, 0x21, 0xaa, 0x0e, 0x0a,
	0x34, 0x21, 0x38, 0x6e, 0x0f, 0xbf, 0x59, 0x10, 0x65, 0x6b, 0x72, 0x0b, 0xce, 0x65, 0x8f, 0x81,
	0xed, 0xec, 0x87, 0xc7, 0x54, 0x39, 0xba, 0x96, 0x89, 0x77, 0x84, 0xd4, 0x7c, 0x02, 0x90, 0x5f,
	0xf1, 0x6f, 0x88, 0xd2, 0xfc, 0x76, 0x19, 0x2e, 0x29, 0x4e, 0xd9, 0x8b, 0x1c, 0x97, 0xa2, 0xff,
	0x32, 0x34, 0xc1, 0xe4, 0x89, 0x90, 0x89, 0x3c, 0xf9, 0x19, 0x93, 0xa3, 0x48, 0x50, 0x61, 0x52,
	0x6a, 0xf9, 0xe5, 0x72, 0xcb, 0xbf, 0xde, 0x2b, 0x73, 0x1b, 0x9a, 0xb2, 0xf7, 0x1a, 0x55, 0xc4,
	0x72, 0xe7, 0x2c, 0xa9, 0x42, 0x3e, 0x84, 0x1b, 0x8a, 0x54, 0xd0, 0x47, 0x49, 0x13, 0x53, 0x27,
	0x99, 0xda, 0x51, 0xe8, 0x1f, 0x38, 0x5e, 0xc8, 0x05, 0xdd, 0x28, 0xae, 0xbf, 0x26, 0xd9, 0x26,
	0xbb, 0xe4, 0x89, 0x93, 0x4c, 0x77, 0x95, 0xda, 0x1e, 0x9b, 0x98, 0xbf, 0x68, 0x00, 0xf9, 0x57,
	0x2c, 0x78, 0x3a, 0xe6, 0x08, 0xa9, 0x6e, 0xe1, 0x1a, 0x9f, 0x2d, 0x36, 0x99, 0x66, 0x98, 0xe2,
	0x86, 0xdc, 0x85, 0x16, 0x5a, 0x4e, 0x9b, 0xf2, 0xd2, 0x6c, 0x53, 0x4a, 0x86, 0x55, 0x6a, 0xf9,
	0xeb, 0xd7, 0x28, 0xbc, 0x7e, 0x95, 0x86, 0x68, 0xe2, 0x55, 0x7f, 0xa7, 0x21, 0xcc, 0x6f, 0x34,
	0xe8, 0x67, 0x11, 0xed, 0x04, 0xde, 0x53, 0x3a, 0xe6, 0x16, 0x7a, 0x36, 0x84, 0xf5, 0x2a, 0x32,
	0xaa, 0x44, 0xd6, 0x92, 0x12, 0x0e, 0x59, 0xb4, 0xcb, 0x75, 0xd1, 0xea, 0xc5, 0x68, 0xfb, 0xd0,
	0x12, 0xef, 0x18, 0xf3, 0x14, 0x15, 0x34, 0x39, 0xa5, 0x23, 0xcf, 0x7c, 0x0f, 0x56, 0x4b, 0xc1,
	0x0a, 0xaa, 0x52, 0xa8, 0x68, 0xf3, 0xa9, 0x4a, 0x6a, 0x98, 0x0f, 0xc0, 0x48, 0x5b, 0x6a, 0xa6,
	0x02, 0x4b, 0xe3, 0x92, 0x56, 0x1d, 0x97, 0x7e, 0xd3, 0xe0, 0xca, 0x9c, 0xda, 0x7d, 0x11, 0x72,
	0x67, 0xe1, 0xc0, 0x74, 0x0f, 0x40, 0xe2, 0xe2, 0xb3, 0x84, 0x2b, 0xf6, 0x2d, 0x50, 0xfd, 0x43,
	0x3f, 0x74, 0x0f, 0x12, 0xe9, 0x68, 0x07, 0x15, 0x9f, 0xb2, 0x84, 0xe7, 0x7d, 0xa5, 0xd7, 0xf5,
	0x55, 0xa3, 0x30, 0x80, 0xa8, 0x9e, 0x6c, 0xe6, 0x3d, 0x59, 0xe9, 0xa6, 0x56, 0xb5, 0x9b, 0xcc,
	0xef, 0x35, 0xe8, 0x16, 0xec, 0x92, 0xcf, 0xe1, 0x72, 0xa1, 0xa8, 0x9d, 0xc0, 0xb3, 0x45, 0x66,
	0x6c, 0x99, 0x16, 0x49, 0x29, 0x85, 0x37, 0xb0, 0xb6, 0x08, 0xac, 0x7e, 0x54, 0x5b, 0x1b, 0x25,
	0x5c, 0xf5, 0x2a, 0xae, 0xbf, 0x6b, 0x70, 0x67, 0x5e, 0x4a, 0x10, 0xd8, 0xbd, 0x54, 0xf5, 0x19,
	0x3d, 0xdc, 0xa7, 0xf1, 0x22, 0x9c, 0x87, 0xb0, 0xce, 0xc5, 0x91, 0x62, 0x15, 0x2a, 0x4e, 0x43,
	0x79, 0x5e, 0x85, 0xff, 0x29, 0xb6, 0xa7, 0x70, 0x75, 0x61, 0x44, 0x8b, 0x42, 0xb8, 0x0e, 0x5d,
	0xe6, 0xf9, 0xd4, 0x8e, 0x69, 0x72, 0xe4, 0xcb, 0x2e, 0x69, 0x5b, 0x20, 0x44, 0x16, 0x4a, 0xce,
	0x40, 0xf3, 0xcf, 0x7c, 0xa8, 0x97, 0x06, 0xcb, 0x4f, 0x45, 0xc6, 0x07, 0x5a, 0x91, 0x0f, 0xee,
	0x43, 0x27, 0xe3, 0x03, 0x35, 0x7d, 0xcd, 0xa7, 0x83, 0x76, 0x4a, 0x07, 0xa5, 0xe7, 0x51, 0x2f,
	0x3d, 0x8f, 0xa5, 0x00, 0x1b, 0x0b, 0xb8, 0xba, 0xf9, 0x7a, 0xbf, 0x08, 0x5a, 0x95, 0xa1, 0x6e,
	0xfb, 0xe7, 0x26, 0xac, 0x88, 0x53, 0x3b, 0x11, 0x23, 0x2f, 0xe1, 0x72, 0x2c, 0x11, 0xb0, 0xe5,
	0x91, 0x09, 0xe5, 0x76, 0x40, 0x4f, 0xec, 0x03, 0x7a, 0x4a, 0x0a, 0x35, 0x5c, 0xfb, 0x53, 0x6f,
	0xb0, 0x51, 0x54, 0xa8, 0xfb, 0x59, 0x67, 0x2e, 0x91, 0xaf, 0xe0, 0x5a, 0xd9, 0x82, 0x9a, 0xe4,
	0x26, 0x34, 0xc0, 0x9a, 0xf0, 0xc9, 0x66, 0xbd, 0x99, 0xf2, 0x4f, 0xac, 0xc1, 0xf9, 0xc2, 0xb4,
	0x97, 0x4e, 0xfb, 0xe6, 0x12, 0x79, 0x05, 0xff, 0x4f, 0xaf, 0x3f, 0xc6, 0x1c, 0xda, 0xc5, 0x49,
	0x91, 0x0c, 0x67, 0xee, 0x9e, 0x33, 0x9f, 0x0f, 0xde, 0x9a, 0x8d, 0x65, 0xc1, 0x1c, 0x61, 0x2e,
	0x91, 0x18, 0x6e, 0xa5, 0x96, 0x8b, 0x6c, 0xae, 0xbc, 0x48, 0x58, 0x30, 0xf1, 0xa9, 0xbd, 0x2f,
	0x58, 0x83, 0xbc, 0x31, 0xe3, 0x45, 0xb5, 0xd4, 0x07, 0xe6, 0xac, 0xf9, 0xaa, 0x8e, 0xb9, 0x44,
	0x42, 0x18, 0x54, 0xa2, 0x95, 0xa6, 0xb1, 0x61, 0xc9, 0xcd, 0x33, 0xcd, 0x60, 0x47, 0x0d, 0x6e,
	0x9d, 0x6d, 0x0b, 0x15, 0xcd, 0x25, 0x72, 0x0c, 0x57, 0x2b, 0x06, 0x3d, 0x05, 0x83, 0x02, 0x78,
	0x73, 0x0e, 0xc0, 0x25, 0xb4, 0xfe, 0x31, 0xb8, 0x0f, 0x57, 0xbf, 0xe8, 0x6e, 0x6d, 0xdd, 0xc5,
	0xda, 0x8f, 0x23, 0x77, 0xbf, 0x85, 0xff, 0x3e, 0xbc, 0xfd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x0c, 0x58, 0x0c, 0x13, 0x8f, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PoisApiClient is the client API for PoisApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PoisApiClient interface {
	RequestMinerGetNewKey(ctx context.Context, in *RequestMinerInitParam, opts ...grpc.CallOption) (*ResponseMinerInitParam, error)
	RequestMinerCommitGenChall(ctx context.Context, in *RequestMinerCommitGenChall, opts ...grpc.CallOption) (*Challenge, error)
	RequestVerifyCommitProof(ctx context.Context, in *RequestVerifyCommitAndAccProof, opts ...grpc.CallOption) (*ResponseVerifyCommitOrDeletionProof, error)
	RequestSpaceProofVerifySingleBlock(ctx context.Context, in *RequestSpaceProofVerify, opts ...grpc.CallOption) (*ResponseSpaceProofVerify, error)
	RequestVerifySpaceTotal(ctx context.Context, in *RequestSpaceProofVerifyTotal, opts ...grpc.CallOption) (*ResponseSpaceProofVerifyTotal, error)
	RequestVerifyDeletionProof(ctx context.Context, in *RequestVerifyDeletionProof, opts ...grpc.CallOption) (*ResponseVerifyCommitOrDeletionProof, error)
}

type poisApiClient struct {
	cc *grpc.ClientConn
}

func NewPoisApiClient(cc *grpc.ClientConn) PoisApiClient {
	return &poisApiClient{cc}
}

func (c *poisApiClient) RequestMinerGetNewKey(ctx context.Context, in *RequestMinerInitParam, opts ...grpc.CallOption) (*ResponseMinerInitParam, error) {
	out := new(ResponseMinerInitParam)
	err := c.cc.Invoke(ctx, "/pois.api.PoisApi/request_miner_get_new_key", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poisApiClient) RequestMinerCommitGenChall(ctx context.Context, in *RequestMinerCommitGenChall, opts ...grpc.CallOption) (*Challenge, error) {
	out := new(Challenge)
	err := c.cc.Invoke(ctx, "/pois.api.PoisApi/request_miner_commit_gen_chall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poisApiClient) RequestVerifyCommitProof(ctx context.Context, in *RequestVerifyCommitAndAccProof, opts ...grpc.CallOption) (*ResponseVerifyCommitOrDeletionProof, error) {
	out := new(ResponseVerifyCommitOrDeletionProof)
	err := c.cc.Invoke(ctx, "/pois.api.PoisApi/request_verify_commit_proof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poisApiClient) RequestSpaceProofVerifySingleBlock(ctx context.Context, in *RequestSpaceProofVerify, opts ...grpc.CallOption) (*ResponseSpaceProofVerify, error) {
	out := new(ResponseSpaceProofVerify)
	err := c.cc.Invoke(ctx, "/pois.api.PoisApi/request_space_proof_verify_single_block", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poisApiClient) RequestVerifySpaceTotal(ctx context.Context, in *RequestSpaceProofVerifyTotal, opts ...grpc.CallOption) (*ResponseSpaceProofVerifyTotal, error) {
	out := new(ResponseSpaceProofVerifyTotal)
	err := c.cc.Invoke(ctx, "/pois.api.PoisApi/request_verify_space_total", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poisApiClient) RequestVerifyDeletionProof(ctx context.Context, in *RequestVerifyDeletionProof, opts ...grpc.CallOption) (*ResponseVerifyCommitOrDeletionProof, error) {
	out := new(ResponseVerifyCommitOrDeletionProof)
	err := c.cc.Invoke(ctx, "/pois.api.PoisApi/request_verify_deletion_proof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoisApiServer is the server API for PoisApi service.
type PoisApiServer interface {
	RequestMinerGetNewKey(context.Context, *RequestMinerInitParam) (*ResponseMinerInitParam, error)
	RequestMinerCommitGenChall(context.Context, *RequestMinerCommitGenChall) (*Challenge, error)
	RequestVerifyCommitProof(context.Context, *RequestVerifyCommitAndAccProof) (*ResponseVerifyCommitOrDeletionProof, error)
	RequestSpaceProofVerifySingleBlock(context.Context, *RequestSpaceProofVerify) (*ResponseSpaceProofVerify, error)
	RequestVerifySpaceTotal(context.Context, *RequestSpaceProofVerifyTotal) (*ResponseSpaceProofVerifyTotal, error)
	RequestVerifyDeletionProof(context.Context, *RequestVerifyDeletionProof) (*ResponseVerifyCommitOrDeletionProof, error)
}

// UnimplementedPoisApiServer can be embedded to have forward compatible implementations.
type UnimplementedPoisApiServer struct {
}

func (*UnimplementedPoisApiServer) RequestMinerGetNewKey(ctx context.Context, req *RequestMinerInitParam) (*ResponseMinerInitParam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMinerGetNewKey not implemented")
}
func (*UnimplementedPoisApiServer) RequestMinerCommitGenChall(ctx context.Context, req *RequestMinerCommitGenChall) (*Challenge, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMinerCommitGenChall not implemented")
}
func (*UnimplementedPoisApiServer) RequestVerifyCommitProof(ctx context.Context, req *RequestVerifyCommitAndAccProof) (*ResponseVerifyCommitOrDeletionProof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVerifyCommitProof not implemented")
}
func (*UnimplementedPoisApiServer) RequestSpaceProofVerifySingleBlock(ctx context.Context, req *RequestSpaceProofVerify) (*ResponseSpaceProofVerify, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestSpaceProofVerifySingleBlock not implemented")
}
func (*UnimplementedPoisApiServer) RequestVerifySpaceTotal(ctx context.Context, req *RequestSpaceProofVerifyTotal) (*ResponseSpaceProofVerifyTotal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVerifySpaceTotal not implemented")
}
func (*UnimplementedPoisApiServer) RequestVerifyDeletionProof(ctx context.Context, req *RequestVerifyDeletionProof) (*ResponseVerifyCommitOrDeletionProof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVerifyDeletionProof not implemented")
}

func RegisterPoisApiServer(s *grpc.Server, srv PoisApiServer) {
	s.RegisterService(&_PoisApi_serviceDesc, srv)
}

func _PoisApi_RequestMinerGetNewKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMinerInitParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoisApiServer).RequestMinerGetNewKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pois.api.PoisApi/RequestMinerGetNewKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoisApiServer).RequestMinerGetNewKey(ctx, req.(*RequestMinerInitParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoisApi_RequestMinerCommitGenChall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMinerCommitGenChall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoisApiServer).RequestMinerCommitGenChall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pois.api.PoisApi/RequestMinerCommitGenChall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoisApiServer).RequestMinerCommitGenChall(ctx, req.(*RequestMinerCommitGenChall))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoisApi_RequestVerifyCommitProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVerifyCommitAndAccProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoisApiServer).RequestVerifyCommitProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pois.api.PoisApi/RequestVerifyCommitProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoisApiServer).RequestVerifyCommitProof(ctx, req.(*RequestVerifyCommitAndAccProof))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoisApi_RequestSpaceProofVerifySingleBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSpaceProofVerify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoisApiServer).RequestSpaceProofVerifySingleBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pois.api.PoisApi/RequestSpaceProofVerifySingleBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoisApiServer).RequestSpaceProofVerifySingleBlock(ctx, req.(*RequestSpaceProofVerify))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoisApi_RequestVerifySpaceTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSpaceProofVerifyTotal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoisApiServer).RequestVerifySpaceTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pois.api.PoisApi/RequestVerifySpaceTotal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoisApiServer).RequestVerifySpaceTotal(ctx, req.(*RequestSpaceProofVerifyTotal))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoisApi_RequestVerifyDeletionProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVerifyDeletionProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoisApiServer).RequestVerifyDeletionProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pois.api.PoisApi/RequestVerifyDeletionProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoisApiServer).RequestVerifyDeletionProof(ctx, req.(*RequestVerifyDeletionProof))
	}
	return interceptor(ctx, in, info, handler)
}

var _PoisApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pois.api.PoisApi",
	HandlerType: (*PoisApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "request_miner_get_new_key",
			Handler:    _PoisApi_RequestMinerGetNewKey_Handler,
		},
		{
			MethodName: "request_miner_commit_gen_chall",
			Handler:    _PoisApi_RequestMinerCommitGenChall_Handler,
		},
		{
			MethodName: "request_verify_commit_proof",
			Handler:    _PoisApi_RequestVerifyCommitProof_Handler,
		},
		{
			MethodName: "request_space_proof_verify_single_block",
			Handler:    _PoisApi_RequestSpaceProofVerifySingleBlock_Handler,
		},
		{
			MethodName: "request_verify_space_total",
			Handler:    _PoisApi_RequestVerifySpaceTotal_Handler,
		},
		{
			MethodName: "request_verify_deletion_proof",
			Handler:    _PoisApi_RequestVerifyDeletionProof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pois_api.proto",
}
