// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: pois_api.proto

package pois_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PoisApi_RequestMinerGetNewKey_FullMethodName      = "/pois.api.PoisApi/request_miner_get_new_key"
	PoisApi_RequestMinerRegister_FullMethodName       = "/pois.api.PoisApi/request_miner_register"
	PoisApi_RequestMinerCommitGenChall_FullMethodName = "/pois.api.PoisApi/request_miner_commit_gen_chall"
	PoisApi_RequestVerifyCommitProof_FullMethodName   = "/pois.api.PoisApi/request_verify_commit_proof"
)

// PoisApiClient is the client API for PoisApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoisApiClient interface {
	RequestMinerGetNewKey(ctx context.Context, in *RequestMinerInitParam, opts ...grpc.CallOption) (*ResponseMinerInitParam, error)
	RequestMinerRegister(ctx context.Context, in *RequestMinerInitParam, opts ...grpc.CallOption) (*ResponseMinerRegister, error)
	RequestMinerCommitGenChall(ctx context.Context, in *RequestMinerCommitGenChall, opts ...grpc.CallOption) (*Challenge, error)
	RequestVerifyCommitProof(ctx context.Context, in *RequestVerifyCommitAndAccProof, opts ...grpc.CallOption) (*ResponseVerifyCommitAndAccProof, error)
}

type poisApiClient struct {
	cc grpc.ClientConnInterface
}

func NewPoisApiClient(cc grpc.ClientConnInterface) PoisApiClient {
	return &poisApiClient{cc}
}

func (c *poisApiClient) RequestMinerGetNewKey(ctx context.Context, in *RequestMinerInitParam, opts ...grpc.CallOption) (*ResponseMinerInitParam, error) {
	out := new(ResponseMinerInitParam)
	err := c.cc.Invoke(ctx, PoisApi_RequestMinerGetNewKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poisApiClient) RequestMinerRegister(ctx context.Context, in *RequestMinerInitParam, opts ...grpc.CallOption) (*ResponseMinerRegister, error) {
	out := new(ResponseMinerRegister)
	err := c.cc.Invoke(ctx, PoisApi_RequestMinerRegister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poisApiClient) RequestMinerCommitGenChall(ctx context.Context, in *RequestMinerCommitGenChall, opts ...grpc.CallOption) (*Challenge, error) {
	out := new(Challenge)
	err := c.cc.Invoke(ctx, PoisApi_RequestMinerCommitGenChall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poisApiClient) RequestVerifyCommitProof(ctx context.Context, in *RequestVerifyCommitAndAccProof, opts ...grpc.CallOption) (*ResponseVerifyCommitAndAccProof, error) {
	out := new(ResponseVerifyCommitAndAccProof)
	err := c.cc.Invoke(ctx, PoisApi_RequestVerifyCommitProof_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoisApiServer is the server API for PoisApi service.
// All implementations must embed UnimplementedPoisApiServer
// for forward compatibility
type PoisApiServer interface {
	RequestMinerGetNewKey(context.Context, *RequestMinerInitParam) (*ResponseMinerInitParam, error)
	RequestMinerRegister(context.Context, *RequestMinerInitParam) (*ResponseMinerRegister, error)
	RequestMinerCommitGenChall(context.Context, *RequestMinerCommitGenChall) (*Challenge, error)
	RequestVerifyCommitProof(context.Context, *RequestVerifyCommitAndAccProof) (*ResponseVerifyCommitAndAccProof, error)
	mustEmbedUnimplementedPoisApiServer()
}

// UnimplementedPoisApiServer must be embedded to have forward compatible implementations.
type UnimplementedPoisApiServer struct {
}

func (UnimplementedPoisApiServer) RequestMinerGetNewKey(context.Context, *RequestMinerInitParam) (*ResponseMinerInitParam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMinerGetNewKey not implemented")
}
func (UnimplementedPoisApiServer) RequestMinerRegister(context.Context, *RequestMinerInitParam) (*ResponseMinerRegister, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMinerRegister not implemented")
}
func (UnimplementedPoisApiServer) RequestMinerCommitGenChall(context.Context, *RequestMinerCommitGenChall) (*Challenge, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMinerCommitGenChall not implemented")
}
func (UnimplementedPoisApiServer) RequestVerifyCommitProof(context.Context, *RequestVerifyCommitAndAccProof) (*ResponseVerifyCommitAndAccProof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVerifyCommitProof not implemented")
}
func (UnimplementedPoisApiServer) mustEmbedUnimplementedPoisApiServer() {}

// UnsafePoisApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoisApiServer will
// result in compilation errors.
type UnsafePoisApiServer interface {
	mustEmbedUnimplementedPoisApiServer()
}

func RegisterPoisApiServer(s grpc.ServiceRegistrar, srv PoisApiServer) {
	s.RegisterService(&PoisApi_ServiceDesc, srv)
}

func _PoisApi_RequestMinerGetNewKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMinerInitParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoisApiServer).RequestMinerGetNewKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoisApi_RequestMinerGetNewKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoisApiServer).RequestMinerGetNewKey(ctx, req.(*RequestMinerInitParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoisApi_RequestMinerRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMinerInitParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoisApiServer).RequestMinerRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoisApi_RequestMinerRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoisApiServer).RequestMinerRegister(ctx, req.(*RequestMinerInitParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoisApi_RequestMinerCommitGenChall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMinerCommitGenChall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoisApiServer).RequestMinerCommitGenChall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoisApi_RequestMinerCommitGenChall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoisApiServer).RequestMinerCommitGenChall(ctx, req.(*RequestMinerCommitGenChall))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoisApi_RequestVerifyCommitProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVerifyCommitAndAccProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoisApiServer).RequestVerifyCommitProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoisApi_RequestVerifyCommitProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoisApiServer).RequestVerifyCommitProof(ctx, req.(*RequestVerifyCommitAndAccProof))
	}
	return interceptor(ctx, in, info, handler)
}

// PoisApi_ServiceDesc is the grpc.ServiceDesc for PoisApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoisApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pois.api.PoisApi",
	HandlerType: (*PoisApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "request_miner_get_new_key",
			Handler:    _PoisApi_RequestMinerGetNewKey_Handler,
		},
		{
			MethodName: "request_miner_register",
			Handler:    _PoisApi_RequestMinerRegister_Handler,
		},
		{
			MethodName: "request_miner_commit_gen_chall",
			Handler:    _PoisApi_RequestMinerCommitGenChall_Handler,
		},
		{
			MethodName: "request_verify_commit_proof",
			Handler:    _PoisApi_RequestVerifyCommitProof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pois_api.proto",
}
