// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pois_api.proto

package pois_rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseMinerRegister struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseMinerRegister) Reset()         { *m = ResponseMinerRegister{} }
func (m *ResponseMinerRegister) String() string { return proto.CompactTextString(m) }
func (*ResponseMinerRegister) ProtoMessage()    {}
func (*ResponseMinerRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{0}
}

func (m *ResponseMinerRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMinerRegister.Unmarshal(m, b)
}
func (m *ResponseMinerRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMinerRegister.Marshal(b, m, deterministic)
}
func (m *ResponseMinerRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMinerRegister.Merge(m, src)
}
func (m *ResponseMinerRegister) XXX_Size() int {
	return xxx_messageInfo_ResponseMinerRegister.Size(m)
}
func (m *ResponseMinerRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMinerRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMinerRegister proto.InternalMessageInfo

func (m *ResponseMinerRegister) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type RequestMinerInitParam struct {
	MinerId              []byte   `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestMinerInitParam) Reset()         { *m = RequestMinerInitParam{} }
func (m *RequestMinerInitParam) String() string { return proto.CompactTextString(m) }
func (*RequestMinerInitParam) ProtoMessage()    {}
func (*RequestMinerInitParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{1}
}

func (m *RequestMinerInitParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMinerInitParam.Unmarshal(m, b)
}
func (m *RequestMinerInitParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMinerInitParam.Marshal(b, m, deterministic)
}
func (m *RequestMinerInitParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMinerInitParam.Merge(m, src)
}
func (m *RequestMinerInitParam) XXX_Size() int {
	return xxx_messageInfo_RequestMinerInitParam.Size(m)
}
func (m *RequestMinerInitParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMinerInitParam.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMinerInitParam proto.InternalMessageInfo

func (m *RequestMinerInitParam) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

type ResponseMinerInitParam struct {
	Acc                  []byte   `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`
	KeyN                 []byte   `protobuf:"bytes,2,opt,name=key_n,json=keyN,proto3" json:"key_n,omitempty"`
	KeyG                 []byte   `protobuf:"bytes,3,opt,name=key_g,json=keyG,proto3" json:"key_g,omitempty"`
	Front                int64    `protobuf:"varint,4,opt,name=front,proto3" json:"front,omitempty"`
	Rear                 int64    `protobuf:"varint,5,opt,name=rear,proto3" json:"rear,omitempty"`
	MinerId              []byte   `protobuf:"bytes,6,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	Signature            []byte   `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseMinerInitParam) Reset()         { *m = ResponseMinerInitParam{} }
func (m *ResponseMinerInitParam) String() string { return proto.CompactTextString(m) }
func (*ResponseMinerInitParam) ProtoMessage()    {}
func (*ResponseMinerInitParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{2}
}

func (m *ResponseMinerInitParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMinerInitParam.Unmarshal(m, b)
}
func (m *ResponseMinerInitParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMinerInitParam.Marshal(b, m, deterministic)
}
func (m *ResponseMinerInitParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMinerInitParam.Merge(m, src)
}
func (m *ResponseMinerInitParam) XXX_Size() int {
	return xxx_messageInfo_ResponseMinerInitParam.Size(m)
}
func (m *ResponseMinerInitParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMinerInitParam.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMinerInitParam proto.InternalMessageInfo

func (m *ResponseMinerInitParam) GetAcc() []byte {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *ResponseMinerInitParam) GetKeyN() []byte {
	if m != nil {
		return m.KeyN
	}
	return nil
}

func (m *ResponseMinerInitParam) GetKeyG() []byte {
	if m != nil {
		return m.KeyG
	}
	return nil
}

func (m *ResponseMinerInitParam) GetFront() int64 {
	if m != nil {
		return m.Front
	}
	return 0
}

func (m *ResponseMinerInitParam) GetRear() int64 {
	if m != nil {
		return m.Rear
	}
	return 0
}

func (m *ResponseMinerInitParam) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *ResponseMinerInitParam) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type RequestMinerCommitGenChall struct {
	MinerId              []byte   `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	Commit               *Commits `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestMinerCommitGenChall) Reset()         { *m = RequestMinerCommitGenChall{} }
func (m *RequestMinerCommitGenChall) String() string { return proto.CompactTextString(m) }
func (*RequestMinerCommitGenChall) ProtoMessage()    {}
func (*RequestMinerCommitGenChall) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{3}
}

func (m *RequestMinerCommitGenChall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMinerCommitGenChall.Unmarshal(m, b)
}
func (m *RequestMinerCommitGenChall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMinerCommitGenChall.Marshal(b, m, deterministic)
}
func (m *RequestMinerCommitGenChall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMinerCommitGenChall.Merge(m, src)
}
func (m *RequestMinerCommitGenChall) XXX_Size() int {
	return xxx_messageInfo_RequestMinerCommitGenChall.Size(m)
}
func (m *RequestMinerCommitGenChall) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMinerCommitGenChall.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMinerCommitGenChall proto.InternalMessageInfo

func (m *RequestMinerCommitGenChall) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *RequestMinerCommitGenChall) GetCommit() *Commits {
	if m != nil {
		return m.Commit
	}
	return nil
}

type Commits struct {
	FileIndexs           []int64  `protobuf:"varint,1,rep,packed,name=file_indexs,json=fileIndexs,proto3" json:"file_indexs,omitempty"`
	Roots                [][]byte `protobuf:"bytes,2,rep,name=roots,proto3" json:"roots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commits) Reset()         { *m = Commits{} }
func (m *Commits) String() string { return proto.CompactTextString(m) }
func (*Commits) ProtoMessage()    {}
func (*Commits) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{4}
}

func (m *Commits) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commits.Unmarshal(m, b)
}
func (m *Commits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commits.Marshal(b, m, deterministic)
}
func (m *Commits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commits.Merge(m, src)
}
func (m *Commits) XXX_Size() int {
	return xxx_messageInfo_Commits.Size(m)
}
func (m *Commits) XXX_DiscardUnknown() {
	xxx_messageInfo_Commits.DiscardUnknown(m)
}

var xxx_messageInfo_Commits proto.InternalMessageInfo

func (m *Commits) GetFileIndexs() []int64 {
	if m != nil {
		return m.FileIndexs
	}
	return nil
}

func (m *Commits) GetRoots() [][]byte {
	if m != nil {
		return m.Roots
	}
	return nil
}

type Challenge struct {
	Rows                 []*Int64Slice `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Challenge) Reset()         { *m = Challenge{} }
func (m *Challenge) String() string { return proto.CompactTextString(m) }
func (*Challenge) ProtoMessage()    {}
func (*Challenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{5}
}

func (m *Challenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Challenge.Unmarshal(m, b)
}
func (m *Challenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Challenge.Marshal(b, m, deterministic)
}
func (m *Challenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Challenge.Merge(m, src)
}
func (m *Challenge) XXX_Size() int {
	return xxx_messageInfo_Challenge.Size(m)
}
func (m *Challenge) XXX_DiscardUnknown() {
	xxx_messageInfo_Challenge.DiscardUnknown(m)
}

var xxx_messageInfo_Challenge proto.InternalMessageInfo

func (m *Challenge) GetRows() []*Int64Slice {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Int64Slice struct {
	Values               []int64  `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Slice) Reset()         { *m = Int64Slice{} }
func (m *Int64Slice) String() string { return proto.CompactTextString(m) }
func (*Int64Slice) ProtoMessage()    {}
func (*Int64Slice) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{6}
}

func (m *Int64Slice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Slice.Unmarshal(m, b)
}
func (m *Int64Slice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Slice.Marshal(b, m, deterministic)
}
func (m *Int64Slice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Slice.Merge(m, src)
}
func (m *Int64Slice) XXX_Size() int {
	return xxx_messageInfo_Int64Slice.Size(m)
}
func (m *Int64Slice) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Slice.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Slice proto.InternalMessageInfo

func (m *Int64Slice) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type RequestVerifyCommitAndAccProof struct {
	CommitProofGroup     *CommitProofGroup `protobuf:"bytes,1,opt,name=commit_proof_group,json=commitProofGroup,proto3" json:"commit_proof_group,omitempty"`
	AccProof             *AccProof         `protobuf:"bytes,2,opt,name=acc_proof,json=accProof,proto3" json:"acc_proof,omitempty"`
	MinerId              []byte            `protobuf:"bytes,3,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	KeyN                 []byte            `protobuf:"bytes,4,opt,name=key_n,json=keyN,proto3" json:"key_n,omitempty"`
	KeyG                 []byte            `protobuf:"bytes,5,opt,name=key_g,json=keyG,proto3" json:"key_g,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RequestVerifyCommitAndAccProof) Reset()         { *m = RequestVerifyCommitAndAccProof{} }
func (m *RequestVerifyCommitAndAccProof) String() string { return proto.CompactTextString(m) }
func (*RequestVerifyCommitAndAccProof) ProtoMessage()    {}
func (*RequestVerifyCommitAndAccProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{7}
}

func (m *RequestVerifyCommitAndAccProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVerifyCommitAndAccProof.Unmarshal(m, b)
}
func (m *RequestVerifyCommitAndAccProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVerifyCommitAndAccProof.Marshal(b, m, deterministic)
}
func (m *RequestVerifyCommitAndAccProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVerifyCommitAndAccProof.Merge(m, src)
}
func (m *RequestVerifyCommitAndAccProof) XXX_Size() int {
	return xxx_messageInfo_RequestVerifyCommitAndAccProof.Size(m)
}
func (m *RequestVerifyCommitAndAccProof) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVerifyCommitAndAccProof.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVerifyCommitAndAccProof proto.InternalMessageInfo

func (m *RequestVerifyCommitAndAccProof) GetCommitProofGroup() *CommitProofGroup {
	if m != nil {
		return m.CommitProofGroup
	}
	return nil
}

func (m *RequestVerifyCommitAndAccProof) GetAccProof() *AccProof {
	if m != nil {
		return m.AccProof
	}
	return nil
}

func (m *RequestVerifyCommitAndAccProof) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *RequestVerifyCommitAndAccProof) GetKeyN() []byte {
	if m != nil {
		return m.KeyN
	}
	return nil
}

func (m *RequestVerifyCommitAndAccProof) GetKeyG() []byte {
	if m != nil {
		return m.KeyG
	}
	return nil
}

type CommitProofGroup struct {
	CommitProofGroupInner []*CommitProofGroupInner `protobuf:"bytes,1,rep,name=commit_proof_group_inner,json=commitProofGroupInner,proto3" json:"commit_proof_group_inner,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                 `json:"-"`
	XXX_unrecognized      []byte                   `json:"-"`
	XXX_sizecache         int32                    `json:"-"`
}

func (m *CommitProofGroup) Reset()         { *m = CommitProofGroup{} }
func (m *CommitProofGroup) String() string { return proto.CompactTextString(m) }
func (*CommitProofGroup) ProtoMessage()    {}
func (*CommitProofGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{8}
}

func (m *CommitProofGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitProofGroup.Unmarshal(m, b)
}
func (m *CommitProofGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitProofGroup.Marshal(b, m, deterministic)
}
func (m *CommitProofGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitProofGroup.Merge(m, src)
}
func (m *CommitProofGroup) XXX_Size() int {
	return xxx_messageInfo_CommitProofGroup.Size(m)
}
func (m *CommitProofGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitProofGroup.DiscardUnknown(m)
}

var xxx_messageInfo_CommitProofGroup proto.InternalMessageInfo

func (m *CommitProofGroup) GetCommitProofGroupInner() []*CommitProofGroupInner {
	if m != nil {
		return m.CommitProofGroupInner
	}
	return nil
}

type CommitProofGroupInner struct {
	CommitProof          []*CommitProof `protobuf:"bytes,1,rep,name=commit_proof,json=commitProof,proto3" json:"commit_proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommitProofGroupInner) Reset()         { *m = CommitProofGroupInner{} }
func (m *CommitProofGroupInner) String() string { return proto.CompactTextString(m) }
func (*CommitProofGroupInner) ProtoMessage()    {}
func (*CommitProofGroupInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{9}
}

func (m *CommitProofGroupInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitProofGroupInner.Unmarshal(m, b)
}
func (m *CommitProofGroupInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitProofGroupInner.Marshal(b, m, deterministic)
}
func (m *CommitProofGroupInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitProofGroupInner.Merge(m, src)
}
func (m *CommitProofGroupInner) XXX_Size() int {
	return xxx_messageInfo_CommitProofGroupInner.Size(m)
}
func (m *CommitProofGroupInner) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitProofGroupInner.DiscardUnknown(m)
}

var xxx_messageInfo_CommitProofGroupInner proto.InternalMessageInfo

func (m *CommitProofGroupInner) GetCommitProof() []*CommitProof {
	if m != nil {
		return m.CommitProof
	}
	return nil
}

type CommitProof struct {
	Node                 *MhtProof   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Parents              []*MhtProof `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CommitProof) Reset()         { *m = CommitProof{} }
func (m *CommitProof) String() string { return proto.CompactTextString(m) }
func (*CommitProof) ProtoMessage()    {}
func (*CommitProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{10}
}

func (m *CommitProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitProof.Unmarshal(m, b)
}
func (m *CommitProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitProof.Marshal(b, m, deterministic)
}
func (m *CommitProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitProof.Merge(m, src)
}
func (m *CommitProof) XXX_Size() int {
	return xxx_messageInfo_CommitProof.Size(m)
}
func (m *CommitProof) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitProof.DiscardUnknown(m)
}

var xxx_messageInfo_CommitProof proto.InternalMessageInfo

func (m *CommitProof) GetNode() *MhtProof {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *CommitProof) GetParents() []*MhtProof {
	if m != nil {
		return m.Parents
	}
	return nil
}

type MhtProof struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Label                []byte   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Paths                [][]byte `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	Locs                 []byte   `protobuf:"bytes,4,opt,name=locs,proto3" json:"locs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MhtProof) Reset()         { *m = MhtProof{} }
func (m *MhtProof) String() string { return proto.CompactTextString(m) }
func (*MhtProof) ProtoMessage()    {}
func (*MhtProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{11}
}

func (m *MhtProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MhtProof.Unmarshal(m, b)
}
func (m *MhtProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MhtProof.Marshal(b, m, deterministic)
}
func (m *MhtProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MhtProof.Merge(m, src)
}
func (m *MhtProof) XXX_Size() int {
	return xxx_messageInfo_MhtProof.Size(m)
}
func (m *MhtProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MhtProof.DiscardUnknown(m)
}

var xxx_messageInfo_MhtProof proto.InternalMessageInfo

func (m *MhtProof) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MhtProof) GetLabel() []byte {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *MhtProof) GetPaths() [][]byte {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *MhtProof) GetLocs() []byte {
	if m != nil {
		return m.Locs
	}
	return nil
}

type AccProof struct {
	Indexs               []int64         `protobuf:"varint,1,rep,packed,name=indexs,proto3" json:"indexs,omitempty"`
	Labels               [][]byte        `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	WitChains            *AccWitnessNode `protobuf:"bytes,3,opt,name=wit_chains,json=witChains,proto3" json:"wit_chains,omitempty"`
	AccPath              [][]byte        `protobuf:"bytes,4,rep,name=acc_path,json=accPath,proto3" json:"acc_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AccProof) Reset()         { *m = AccProof{} }
func (m *AccProof) String() string { return proto.CompactTextString(m) }
func (*AccProof) ProtoMessage()    {}
func (*AccProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{12}
}

func (m *AccProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccProof.Unmarshal(m, b)
}
func (m *AccProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccProof.Marshal(b, m, deterministic)
}
func (m *AccProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccProof.Merge(m, src)
}
func (m *AccProof) XXX_Size() int {
	return xxx_messageInfo_AccProof.Size(m)
}
func (m *AccProof) XXX_DiscardUnknown() {
	xxx_messageInfo_AccProof.DiscardUnknown(m)
}

var xxx_messageInfo_AccProof proto.InternalMessageInfo

func (m *AccProof) GetIndexs() []int64 {
	if m != nil {
		return m.Indexs
	}
	return nil
}

func (m *AccProof) GetLabels() [][]byte {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *AccProof) GetWitChains() *AccWitnessNode {
	if m != nil {
		return m.WitChains
	}
	return nil
}

func (m *AccProof) GetAccPath() [][]byte {
	if m != nil {
		return m.AccPath
	}
	return nil
}

type AccWitnessNode struct {
	Elem                 []byte          `protobuf:"bytes,1,opt,name=elem,proto3" json:"elem,omitempty"`
	Wit                  []byte          `protobuf:"bytes,2,opt,name=wit,proto3" json:"wit,omitempty"`
	Acc                  *AccWitnessNode `protobuf:"bytes,3,opt,name=acc,proto3" json:"acc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AccWitnessNode) Reset()         { *m = AccWitnessNode{} }
func (m *AccWitnessNode) String() string { return proto.CompactTextString(m) }
func (*AccWitnessNode) ProtoMessage()    {}
func (*AccWitnessNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{13}
}

func (m *AccWitnessNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccWitnessNode.Unmarshal(m, b)
}
func (m *AccWitnessNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccWitnessNode.Marshal(b, m, deterministic)
}
func (m *AccWitnessNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccWitnessNode.Merge(m, src)
}
func (m *AccWitnessNode) XXX_Size() int {
	return xxx_messageInfo_AccWitnessNode.Size(m)
}
func (m *AccWitnessNode) XXX_DiscardUnknown() {
	xxx_messageInfo_AccWitnessNode.DiscardUnknown(m)
}

var xxx_messageInfo_AccWitnessNode proto.InternalMessageInfo

func (m *AccWitnessNode) GetElem() []byte {
	if m != nil {
		return m.Elem
	}
	return nil
}

func (m *AccWitnessNode) GetWit() []byte {
	if m != nil {
		return m.Wit
	}
	return nil
}

func (m *AccWitnessNode) GetAcc() *AccWitnessNode {
	if m != nil {
		return m.Acc
	}
	return nil
}

type ResponseVerifyCommitOrDeletionProof struct {
	PoisStatus           *PoisStatus `protobuf:"bytes,1,opt,name=pois_status,json=poisStatus,proto3" json:"pois_status,omitempty"`
	SignatureAbove       []byte      `protobuf:"bytes,2,opt,name=signature_above,json=signatureAbove,proto3" json:"signature_above,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResponseVerifyCommitOrDeletionProof) Reset()         { *m = ResponseVerifyCommitOrDeletionProof{} }
func (m *ResponseVerifyCommitOrDeletionProof) String() string { return proto.CompactTextString(m) }
func (*ResponseVerifyCommitOrDeletionProof) ProtoMessage()    {}
func (*ResponseVerifyCommitOrDeletionProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{14}
}

func (m *ResponseVerifyCommitOrDeletionProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseVerifyCommitOrDeletionProof.Unmarshal(m, b)
}
func (m *ResponseVerifyCommitOrDeletionProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseVerifyCommitOrDeletionProof.Marshal(b, m, deterministic)
}
func (m *ResponseVerifyCommitOrDeletionProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseVerifyCommitOrDeletionProof.Merge(m, src)
}
func (m *ResponseVerifyCommitOrDeletionProof) XXX_Size() int {
	return xxx_messageInfo_ResponseVerifyCommitOrDeletionProof.Size(m)
}
func (m *ResponseVerifyCommitOrDeletionProof) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseVerifyCommitOrDeletionProof.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseVerifyCommitOrDeletionProof proto.InternalMessageInfo

func (m *ResponseVerifyCommitOrDeletionProof) GetPoisStatus() *PoisStatus {
	if m != nil {
		return m.PoisStatus
	}
	return nil
}

func (m *ResponseVerifyCommitOrDeletionProof) GetSignatureAbove() []byte {
	if m != nil {
		return m.SignatureAbove
	}
	return nil
}

type PoisStatus struct {
	Acc                  []byte   `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`
	Front                int64    `protobuf:"varint,2,opt,name=front,proto3" json:"front,omitempty"`
	Rear                 int64    `protobuf:"varint,3,opt,name=rear,proto3" json:"rear,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoisStatus) Reset()         { *m = PoisStatus{} }
func (m *PoisStatus) String() string { return proto.CompactTextString(m) }
func (*PoisStatus) ProtoMessage()    {}
func (*PoisStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{15}
}

func (m *PoisStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoisStatus.Unmarshal(m, b)
}
func (m *PoisStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoisStatus.Marshal(b, m, deterministic)
}
func (m *PoisStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoisStatus.Merge(m, src)
}
func (m *PoisStatus) XXX_Size() int {
	return xxx_messageInfo_PoisStatus.Size(m)
}
func (m *PoisStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PoisStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PoisStatus proto.InternalMessageInfo

func (m *PoisStatus) GetAcc() []byte {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *PoisStatus) GetFront() int64 {
	if m != nil {
		return m.Front
	}
	return 0
}

func (m *PoisStatus) GetRear() int64 {
	if m != nil {
		return m.Rear
	}
	return 0
}

type RequestSpaceProofVerify struct {
	SpaceChals                     []int64     `protobuf:"varint,1,rep,packed,name=space_chals,json=spaceChals,proto3" json:"space_chals,omitempty"`
	MinerId                        []byte      `protobuf:"bytes,2,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	KeyN                           []byte      `protobuf:"bytes,3,opt,name=key_n,json=keyN,proto3" json:"key_n,omitempty"`
	KeyG                           []byte      `protobuf:"bytes,4,opt,name=key_g,json=keyG,proto3" json:"key_g,omitempty"`
	Acc                            []byte      `protobuf:"bytes,5,opt,name=acc,proto3" json:"acc,omitempty"`
	Front                          int64       `protobuf:"varint,6,opt,name=front,proto3" json:"front,omitempty"`
	Rear                           int64       `protobuf:"varint,7,opt,name=rear,proto3" json:"rear,omitempty"`
	Proof                          *SpaceProof `protobuf:"bytes,8,opt,name=proof,proto3" json:"proof,omitempty"`
	MinerSpaceProofHashPolkadotSig []byte      `protobuf:"bytes,9,opt,name=miner_space_proof_hash_polkadot_sig,json=minerSpaceProofHashPolkadotSig,proto3" json:"miner_space_proof_hash_polkadot_sig,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}    `json:"-"`
	XXX_unrecognized               []byte      `json:"-"`
	XXX_sizecache                  int32       `json:"-"`
}

func (m *RequestSpaceProofVerify) Reset()         { *m = RequestSpaceProofVerify{} }
func (m *RequestSpaceProofVerify) String() string { return proto.CompactTextString(m) }
func (*RequestSpaceProofVerify) ProtoMessage()    {}
func (*RequestSpaceProofVerify) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{16}
}

func (m *RequestSpaceProofVerify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSpaceProofVerify.Unmarshal(m, b)
}
func (m *RequestSpaceProofVerify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSpaceProofVerify.Marshal(b, m, deterministic)
}
func (m *RequestSpaceProofVerify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSpaceProofVerify.Merge(m, src)
}
func (m *RequestSpaceProofVerify) XXX_Size() int {
	return xxx_messageInfo_RequestSpaceProofVerify.Size(m)
}
func (m *RequestSpaceProofVerify) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSpaceProofVerify.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSpaceProofVerify proto.InternalMessageInfo

func (m *RequestSpaceProofVerify) GetSpaceChals() []int64 {
	if m != nil {
		return m.SpaceChals
	}
	return nil
}

func (m *RequestSpaceProofVerify) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *RequestSpaceProofVerify) GetKeyN() []byte {
	if m != nil {
		return m.KeyN
	}
	return nil
}

func (m *RequestSpaceProofVerify) GetKeyG() []byte {
	if m != nil {
		return m.KeyG
	}
	return nil
}

func (m *RequestSpaceProofVerify) GetAcc() []byte {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *RequestSpaceProofVerify) GetFront() int64 {
	if m != nil {
		return m.Front
	}
	return 0
}

func (m *RequestSpaceProofVerify) GetRear() int64 {
	if m != nil {
		return m.Rear
	}
	return 0
}

func (m *RequestSpaceProofVerify) GetProof() *SpaceProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *RequestSpaceProofVerify) GetMinerSpaceProofHashPolkadotSig() []byte {
	if m != nil {
		return m.MinerSpaceProofHashPolkadotSig
	}
	return nil
}

type SpaceProof struct {
	Left                 int64             `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	Right                int64             `protobuf:"varint,2,opt,name=right,proto3" json:"right,omitempty"`
	Proofs               []*MhtProofGroup  `protobuf:"bytes,3,rep,name=proofs,proto3" json:"proofs,omitempty"`
	Roots                [][]byte          `protobuf:"bytes,4,rep,name=roots,proto3" json:"roots,omitempty"`
	WitChains            []*AccWitnessNode `protobuf:"bytes,5,rep,name=wit_chains,json=witChains,proto3" json:"wit_chains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SpaceProof) Reset()         { *m = SpaceProof{} }
func (m *SpaceProof) String() string { return proto.CompactTextString(m) }
func (*SpaceProof) ProtoMessage()    {}
func (*SpaceProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{17}
}

func (m *SpaceProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceProof.Unmarshal(m, b)
}
func (m *SpaceProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceProof.Marshal(b, m, deterministic)
}
func (m *SpaceProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceProof.Merge(m, src)
}
func (m *SpaceProof) XXX_Size() int {
	return xxx_messageInfo_SpaceProof.Size(m)
}
func (m *SpaceProof) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceProof.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceProof proto.InternalMessageInfo

func (m *SpaceProof) GetLeft() int64 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *SpaceProof) GetRight() int64 {
	if m != nil {
		return m.Right
	}
	return 0
}

func (m *SpaceProof) GetProofs() []*MhtProofGroup {
	if m != nil {
		return m.Proofs
	}
	return nil
}

func (m *SpaceProof) GetRoots() [][]byte {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *SpaceProof) GetWitChains() []*AccWitnessNode {
	if m != nil {
		return m.WitChains
	}
	return nil
}

type ProofHashAndLeftRight struct {
	SpaceProofHash       []byte   `protobuf:"bytes,1,opt,name=space_proof_hash,json=spaceProofHash,proto3" json:"space_proof_hash,omitempty"`
	Left                 int64    `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`
	Right                int64    `protobuf:"varint,3,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofHashAndLeftRight) Reset()         { *m = ProofHashAndLeftRight{} }
func (m *ProofHashAndLeftRight) String() string { return proto.CompactTextString(m) }
func (*ProofHashAndLeftRight) ProtoMessage()    {}
func (*ProofHashAndLeftRight) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{18}
}

func (m *ProofHashAndLeftRight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofHashAndLeftRight.Unmarshal(m, b)
}
func (m *ProofHashAndLeftRight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofHashAndLeftRight.Marshal(b, m, deterministic)
}
func (m *ProofHashAndLeftRight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofHashAndLeftRight.Merge(m, src)
}
func (m *ProofHashAndLeftRight) XXX_Size() int {
	return xxx_messageInfo_ProofHashAndLeftRight.Size(m)
}
func (m *ProofHashAndLeftRight) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofHashAndLeftRight.DiscardUnknown(m)
}

var xxx_messageInfo_ProofHashAndLeftRight proto.InternalMessageInfo

func (m *ProofHashAndLeftRight) GetSpaceProofHash() []byte {
	if m != nil {
		return m.SpaceProofHash
	}
	return nil
}

func (m *ProofHashAndLeftRight) GetLeft() int64 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *ProofHashAndLeftRight) GetRight() int64 {
	if m != nil {
		return m.Right
	}
	return 0
}

type MhtProofGroup struct {
	Proofs               []*MhtProof `protobuf:"bytes,1,rep,name=proofs,proto3" json:"proofs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MhtProofGroup) Reset()         { *m = MhtProofGroup{} }
func (m *MhtProofGroup) String() string { return proto.CompactTextString(m) }
func (*MhtProofGroup) ProtoMessage()    {}
func (*MhtProofGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{19}
}

func (m *MhtProofGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MhtProofGroup.Unmarshal(m, b)
}
func (m *MhtProofGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MhtProofGroup.Marshal(b, m, deterministic)
}
func (m *MhtProofGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MhtProofGroup.Merge(m, src)
}
func (m *MhtProofGroup) XXX_Size() int {
	return xxx_messageInfo_MhtProofGroup.Size(m)
}
func (m *MhtProofGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_MhtProofGroup.DiscardUnknown(m)
}

var xxx_messageInfo_MhtProofGroup proto.InternalMessageInfo

func (m *MhtProofGroup) GetProofs() []*MhtProof {
	if m != nil {
		return m.Proofs
	}
	return nil
}

type ResponseSpaceProofVerify struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSpaceProofVerify) Reset()         { *m = ResponseSpaceProofVerify{} }
func (m *ResponseSpaceProofVerify) String() string { return proto.CompactTextString(m) }
func (*ResponseSpaceProofVerify) ProtoMessage()    {}
func (*ResponseSpaceProofVerify) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{20}
}

func (m *ResponseSpaceProofVerify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSpaceProofVerify.Unmarshal(m, b)
}
func (m *ResponseSpaceProofVerify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSpaceProofVerify.Marshal(b, m, deterministic)
}
func (m *ResponseSpaceProofVerify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSpaceProofVerify.Merge(m, src)
}
func (m *ResponseSpaceProofVerify) XXX_Size() int {
	return xxx_messageInfo_ResponseSpaceProofVerify.Size(m)
}
func (m *ResponseSpaceProofVerify) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSpaceProofVerify.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSpaceProofVerify proto.InternalMessageInfo

func (m *ResponseSpaceProofVerify) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type RequestSpaceProofVerifyTotal struct {
	MinerId              []byte         `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	ProofList            []*BlocksProof `protobuf:"bytes,2,rep,name=proof_list,json=proofList,proto3" json:"proof_list,omitempty"`
	Front                int64          `protobuf:"varint,3,opt,name=front,proto3" json:"front,omitempty"`
	Rear                 int64          `protobuf:"varint,4,opt,name=rear,proto3" json:"rear,omitempty"`
	Acc                  []byte         `protobuf:"bytes,5,opt,name=acc,proto3" json:"acc,omitempty"`
	SpaceChals           []int64        `protobuf:"varint,6,rep,packed,name=space_chals,json=spaceChals,proto3" json:"space_chals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RequestSpaceProofVerifyTotal) Reset()         { *m = RequestSpaceProofVerifyTotal{} }
func (m *RequestSpaceProofVerifyTotal) String() string { return proto.CompactTextString(m) }
func (*RequestSpaceProofVerifyTotal) ProtoMessage()    {}
func (*RequestSpaceProofVerifyTotal) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{21}
}

func (m *RequestSpaceProofVerifyTotal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSpaceProofVerifyTotal.Unmarshal(m, b)
}
func (m *RequestSpaceProofVerifyTotal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSpaceProofVerifyTotal.Marshal(b, m, deterministic)
}
func (m *RequestSpaceProofVerifyTotal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSpaceProofVerifyTotal.Merge(m, src)
}
func (m *RequestSpaceProofVerifyTotal) XXX_Size() int {
	return xxx_messageInfo_RequestSpaceProofVerifyTotal.Size(m)
}
func (m *RequestSpaceProofVerifyTotal) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSpaceProofVerifyTotal.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSpaceProofVerifyTotal proto.InternalMessageInfo

func (m *RequestSpaceProofVerifyTotal) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *RequestSpaceProofVerifyTotal) GetProofList() []*BlocksProof {
	if m != nil {
		return m.ProofList
	}
	return nil
}

func (m *RequestSpaceProofVerifyTotal) GetFront() int64 {
	if m != nil {
		return m.Front
	}
	return 0
}

func (m *RequestSpaceProofVerifyTotal) GetRear() int64 {
	if m != nil {
		return m.Rear
	}
	return 0
}

func (m *RequestSpaceProofVerifyTotal) GetAcc() []byte {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *RequestSpaceProofVerifyTotal) GetSpaceChals() []int64 {
	if m != nil {
		return m.SpaceChals
	}
	return nil
}

type BlocksProof struct {
	ProofHashAndLeftRight *ProofHashAndLeftRight `protobuf:"bytes,1,opt,name=proof_hash_and_left_right,json=proofHashAndLeftRight,proto3" json:"proof_hash_and_left_right,omitempty"`
	Signature             []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *BlocksProof) Reset()         { *m = BlocksProof{} }
func (m *BlocksProof) String() string { return proto.CompactTextString(m) }
func (*BlocksProof) ProtoMessage()    {}
func (*BlocksProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{22}
}

func (m *BlocksProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksProof.Unmarshal(m, b)
}
func (m *BlocksProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksProof.Marshal(b, m, deterministic)
}
func (m *BlocksProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksProof.Merge(m, src)
}
func (m *BlocksProof) XXX_Size() int {
	return xxx_messageInfo_BlocksProof.Size(m)
}
func (m *BlocksProof) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksProof.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksProof proto.InternalMessageInfo

func (m *BlocksProof) GetProofHashAndLeftRight() *ProofHashAndLeftRight {
	if m != nil {
		return m.ProofHashAndLeftRight
	}
	return nil
}

func (m *BlocksProof) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ResponseSpaceProofVerifyTotalSignatureMember struct {
	MinerId              []byte   `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	TotalProofHash       []byte   `protobuf:"bytes,2,opt,name=total_proof_hash,json=totalProofHash,proto3" json:"total_proof_hash,omitempty"`
	Front                int64    `protobuf:"varint,3,opt,name=front,proto3" json:"front,omitempty"`
	Rear                 int64    `protobuf:"varint,4,opt,name=rear,proto3" json:"rear,omitempty"`
	Acc                  []byte   `protobuf:"bytes,5,opt,name=acc,proto3" json:"acc,omitempty"`
	SpaceChals           []int64  `protobuf:"varint,6,rep,packed,name=space_chals,json=spaceChals,proto3" json:"space_chals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) Reset() {
	*m = ResponseSpaceProofVerifyTotalSignatureMember{}
}
func (m *ResponseSpaceProofVerifyTotalSignatureMember) String() string {
	return proto.CompactTextString(m)
}
func (*ResponseSpaceProofVerifyTotalSignatureMember) ProtoMessage() {}
func (*ResponseSpaceProofVerifyTotalSignatureMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{23}
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember.Unmarshal(m, b)
}
func (m *ResponseSpaceProofVerifyTotalSignatureMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember.Marshal(b, m, deterministic)
}
func (m *ResponseSpaceProofVerifyTotalSignatureMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember.Merge(m, src)
}
func (m *ResponseSpaceProofVerifyTotalSignatureMember) XXX_Size() int {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember.Size(m)
}
func (m *ResponseSpaceProofVerifyTotalSignatureMember) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSpaceProofVerifyTotalSignatureMember proto.InternalMessageInfo

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetTotalProofHash() []byte {
	if m != nil {
		return m.TotalProofHash
	}
	return nil
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetFront() int64 {
	if m != nil {
		return m.Front
	}
	return 0
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetRear() int64 {
	if m != nil {
		return m.Rear
	}
	return 0
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetAcc() []byte {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *ResponseSpaceProofVerifyTotalSignatureMember) GetSpaceChals() []int64 {
	if m != nil {
		return m.SpaceChals
	}
	return nil
}

type ResponseSpaceProofVerifyTotal struct {
	MinerId              []byte   `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	IdleResult           bool     `protobuf:"varint,2,opt,name=idle_result,json=idleResult,proto3" json:"idle_result,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSpaceProofVerifyTotal) Reset()         { *m = ResponseSpaceProofVerifyTotal{} }
func (m *ResponseSpaceProofVerifyTotal) String() string { return proto.CompactTextString(m) }
func (*ResponseSpaceProofVerifyTotal) ProtoMessage()    {}
func (*ResponseSpaceProofVerifyTotal) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{24}
}

func (m *ResponseSpaceProofVerifyTotal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotal.Unmarshal(m, b)
}
func (m *ResponseSpaceProofVerifyTotal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotal.Marshal(b, m, deterministic)
}
func (m *ResponseSpaceProofVerifyTotal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSpaceProofVerifyTotal.Merge(m, src)
}
func (m *ResponseSpaceProofVerifyTotal) XXX_Size() int {
	return xxx_messageInfo_ResponseSpaceProofVerifyTotal.Size(m)
}
func (m *ResponseSpaceProofVerifyTotal) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSpaceProofVerifyTotal.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSpaceProofVerifyTotal proto.InternalMessageInfo

func (m *ResponseSpaceProofVerifyTotal) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *ResponseSpaceProofVerifyTotal) GetIdleResult() bool {
	if m != nil {
		return m.IdleResult
	}
	return false
}

func (m *ResponseSpaceProofVerifyTotal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type RequestVerifyDeletionProof struct {
	Roots                [][]byte        `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	WitChain             *AccWitnessNode `protobuf:"bytes,2,opt,name=wit_chain,json=witChain,proto3" json:"wit_chain,omitempty"`
	AccPath              [][]byte        `protobuf:"bytes,3,rep,name=acc_path,json=accPath,proto3" json:"acc_path,omitempty"`
	MinerId              []byte          `protobuf:"bytes,4,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	KeyN                 []byte          `protobuf:"bytes,5,opt,name=key_n,json=keyN,proto3" json:"key_n,omitempty"`
	KeyG                 []byte          `protobuf:"bytes,6,opt,name=key_g,json=keyG,proto3" json:"key_g,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RequestVerifyDeletionProof) Reset()         { *m = RequestVerifyDeletionProof{} }
func (m *RequestVerifyDeletionProof) String() string { return proto.CompactTextString(m) }
func (*RequestVerifyDeletionProof) ProtoMessage()    {}
func (*RequestVerifyDeletionProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea31f2b7d8186a5c, []int{25}
}

func (m *RequestVerifyDeletionProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVerifyDeletionProof.Unmarshal(m, b)
}
func (m *RequestVerifyDeletionProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVerifyDeletionProof.Marshal(b, m, deterministic)
}
func (m *RequestVerifyDeletionProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVerifyDeletionProof.Merge(m, src)
}
func (m *RequestVerifyDeletionProof) XXX_Size() int {
	return xxx_messageInfo_RequestVerifyDeletionProof.Size(m)
}
func (m *RequestVerifyDeletionProof) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVerifyDeletionProof.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVerifyDeletionProof proto.InternalMessageInfo

func (m *RequestVerifyDeletionProof) GetRoots() [][]byte {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *RequestVerifyDeletionProof) GetWitChain() *AccWitnessNode {
	if m != nil {
		return m.WitChain
	}
	return nil
}

func (m *RequestVerifyDeletionProof) GetAccPath() [][]byte {
	if m != nil {
		return m.AccPath
	}
	return nil
}

func (m *RequestVerifyDeletionProof) GetMinerId() []byte {
	if m != nil {
		return m.MinerId
	}
	return nil
}

func (m *RequestVerifyDeletionProof) GetKeyN() []byte {
	if m != nil {
		return m.KeyN
	}
	return nil
}

func (m *RequestVerifyDeletionProof) GetKeyG() []byte {
	if m != nil {
		return m.KeyG
	}
	return nil
}

func init() {
	proto.RegisterType((*ResponseMinerRegister)(nil), "pois.api.ResponseMinerRegister")
	proto.RegisterType((*RequestMinerInitParam)(nil), "pois.api.RequestMinerInitParam")
	proto.RegisterType((*ResponseMinerInitParam)(nil), "pois.api.ResponseMinerInitParam")
	proto.RegisterType((*RequestMinerCommitGenChall)(nil), "pois.api.RequestMinerCommitGenChall")
	proto.RegisterType((*Commits)(nil), "pois.api.Commits")
	proto.RegisterType((*Challenge)(nil), "pois.api.Challenge")
	proto.RegisterType((*Int64Slice)(nil), "pois.api.Int64Slice")
	proto.RegisterType((*RequestVerifyCommitAndAccProof)(nil), "pois.api.RequestVerifyCommitAndAccProof")
	proto.RegisterType((*CommitProofGroup)(nil), "pois.api.CommitProofGroup")
	proto.RegisterType((*CommitProofGroupInner)(nil), "pois.api.CommitProofGroupInner")
	proto.RegisterType((*CommitProof)(nil), "pois.api.CommitProof")
	proto.RegisterType((*MhtProof)(nil), "pois.api.MhtProof")
	proto.RegisterType((*AccProof)(nil), "pois.api.AccProof")
	proto.RegisterType((*AccWitnessNode)(nil), "pois.api.AccWitnessNode")
	proto.RegisterType((*ResponseVerifyCommitOrDeletionProof)(nil), "pois.api.ResponseVerifyCommitOrDeletionProof")
	proto.RegisterType((*PoisStatus)(nil), "pois.api.PoisStatus")
	proto.RegisterType((*RequestSpaceProofVerify)(nil), "pois.api.RequestSpaceProofVerify")
	proto.RegisterType((*SpaceProof)(nil), "pois.api.SpaceProof")
	proto.RegisterType((*ProofHashAndLeftRight)(nil), "pois.api.ProofHashAndLeftRight")
	proto.RegisterType((*MhtProofGroup)(nil), "pois.api.MhtProofGroup")
	proto.RegisterType((*ResponseSpaceProofVerify)(nil), "pois.api.ResponseSpaceProofVerify")
	proto.RegisterType((*RequestSpaceProofVerifyTotal)(nil), "pois.api.RequestSpaceProofVerifyTotal")
	proto.RegisterType((*BlocksProof)(nil), "pois.api.BlocksProof")
	proto.RegisterType((*ResponseSpaceProofVerifyTotalSignatureMember)(nil), "pois.api.ResponseSpaceProofVerifyTotalSignatureMember")
	proto.RegisterType((*ResponseSpaceProofVerifyTotal)(nil), "pois.api.ResponseSpaceProofVerifyTotal")
	proto.RegisterType((*RequestVerifyDeletionProof)(nil), "pois.api.RequestVerifyDeletionProof")
}

func init() { proto.RegisterFile("pois_api.proto", fileDescriptor_ea31f2b7d8186a5c) }

var fileDescriptor_ea31f2b7d8186a5c = []byte{
	// 1378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0xdc, 0xc4,
	0x17, 0x8f, 0xe3, 0xfd, 0x3c, 0x9b, 0xe6, 0x9f, 0xff, 0xb4, 0x49, 0xdd, 0xa5, 0x6d, 0xc2, 0xb4,
	0x6a, 0x97, 0xaa, 0x24, 0xd2, 0xd2, 0x42, 0x25, 0x6e, 0x48, 0x8b, 0xd4, 0x46, 0x34, 0x25, 0x38,
	0x88, 0x2f, 0x81, 0xdc, 0x59, 0xef, 0x64, 0x77, 0x14, 0xc7, 0x36, 0x9e, 0x49, 0xd2, 0x3c, 0x00,
	0x5c, 0xf2, 0x34, 0x08, 0x9e, 0x01, 0x89, 0x0b, 0x1e, 0x81, 0x37, 0x01, 0xcd, 0x87, 0x3f, 0xd7,
	0xbb, 0x81, 0x0b, 0xee, 0xe6, 0x1c, 0x9f, 0x39, 0x5f, 0x73, 0x7e, 0xbf, 0x19, 0xc3, 0x6a, 0x1c,
	0x31, 0xee, 0x91, 0x98, 0x6d, 0xc7, 0x49, 0x24, 0x22, 0xd4, 0x91, 0xf2, 0x36, 0x89, 0x19, 0xde,
	0x81, 0x75, 0x97, 0xf2, 0x38, 0x0a, 0x39, 0xdd, 0x67, 0x21, 0x4d, 0x5c, 0x3a, 0x61, 0x5c, 0xd0,
	0x04, 0x6d, 0x40, 0x8b, 0x0b, 0x22, 0x4e, 0xb9, 0x63, 0x6d, 0x59, 0x83, 0x8e, 0x6b, 0x24, 0x3c,
	0x94, 0x1b, 0xbe, 0x3f, 0xa5, 0x5c, 0x28, 0xfb, 0xbd, 0x90, 0x89, 0x03, 0x92, 0x90, 0x13, 0x74,
	0x03, 0x3a, 0x27, 0x52, 0xe3, 0xb1, 0xb1, 0xda, 0xb2, 0xe2, 0xb6, 0x95, 0xbc, 0x37, 0xc6, 0xbf,
	0x5a, 0xb0, 0x51, 0x8a, 0x92, 0xef, 0x5a, 0x03, 0x9b, 0xf8, 0xbe, 0xd9, 0x20, 0x97, 0xe8, 0x2a,
	0x34, 0x8f, 0xe9, 0x85, 0x17, 0x3a, 0xcb, 0x4a, 0xd7, 0x38, 0xa6, 0x17, 0xaf, 0x52, 0xe5, 0xc4,
	0xb1, 0x33, 0xe5, 0x73, 0x74, 0x0d, 0x9a, 0x47, 0x49, 0x14, 0x0a, 0xa7, 0xb1, 0x65, 0x0d, 0x6c,
	0x57, 0x0b, 0x08, 0x41, 0x23, 0xa1, 0x24, 0x71, 0x9a, 0x4a, 0xa9, 0xd6, 0xa5, 0xdc, 0x5a, 0xa5,
	0xdc, 0xd0, 0x4d, 0xe8, 0x72, 0x36, 0x09, 0x89, 0x38, 0x4d, 0xa8, 0xd3, 0x56, 0xdf, 0x72, 0x05,
	0x1e, 0x41, 0xbf, 0x58, 0xed, 0xb3, 0xe8, 0xe4, 0x84, 0x89, 0xe7, 0x34, 0x7c, 0x36, 0x25, 0x41,
	0xb0, 0xa0, 0x64, 0xf4, 0x0e, 0xb4, 0x7c, 0x65, 0xac, 0xca, 0xe8, 0x0d, 0xff, 0xbf, 0x9d, 0xb6,
	0x7c, 0x5b, 0x3b, 0xe1, 0xae, 0x31, 0xc0, 0x1f, 0x41, 0xdb, 0xa8, 0xd0, 0x26, 0xf4, 0x8e, 0x58,
	0x40, 0x3d, 0x16, 0x8e, 0xe9, 0x1b, 0xd9, 0x79, 0x7b, 0x60, 0xbb, 0x20, 0x55, 0x7b, 0x4a, 0x23,
	0x4b, 0x4e, 0xa2, 0x48, 0x70, 0x67, 0x79, 0xcb, 0x1e, 0xac, 0xb8, 0x5a, 0xc0, 0x8f, 0xa1, 0xab,
	0x12, 0xa2, 0xe1, 0x84, 0xa2, 0x01, 0x34, 0x92, 0xe8, 0x5c, 0x6f, 0xee, 0x0d, 0xaf, 0xe5, 0x71,
	0xf7, 0x42, 0xf1, 0xfe, 0xa3, 0xc3, 0x80, 0xf9, 0xd4, 0x55, 0x16, 0xf8, 0x2e, 0x40, 0xae, 0x93,
	0x07, 0x7e, 0x46, 0x82, 0x53, 0x9a, 0x86, 0x35, 0x12, 0xfe, 0xd3, 0x82, 0xdb, 0xa6, 0x07, 0x5f,
	0xd0, 0x84, 0x1d, 0x5d, 0xe8, 0x64, 0x77, 0xc3, 0xf1, 0xae, 0xef, 0x1f, 0x24, 0x51, 0x74, 0x84,
	0x5e, 0x00, 0xd2, 0xb5, 0x78, 0xb1, 0x94, 0xbd, 0x49, 0x12, 0x9d, 0xc6, 0xaa, 0x23, 0xbd, 0x61,
	0xbf, 0x5a, 0xb8, 0xda, 0xf2, 0x5c, 0x5a, 0xb8, 0x6b, 0x7e, 0x45, 0x83, 0x76, 0xa0, 0x4b, 0x7c,
	0x5f, 0xbb, 0x31, 0x9d, 0x43, 0xb9, 0x83, 0x34, 0xa0, 0xdb, 0x21, 0x69, 0xe8, 0xe2, 0x11, 0xd8,
	0xe5, 0x23, 0xc8, 0x06, 0xa9, 0x51, 0x37, 0x48, 0xcd, 0x7c, 0x90, 0x70, 0x00, 0x6b, 0xd5, 0xdc,
	0xd0, 0x57, 0xe0, 0xcc, 0xd6, 0xe4, 0xb1, 0x30, 0xa4, 0x89, 0x69, 0xed, 0xe6, 0xfc, 0xca, 0xf6,
	0xa4, 0x99, 0xbb, 0xee, 0xd7, 0xa9, 0xf1, 0x67, 0xb0, 0x5e, 0x6b, 0x8f, 0x9e, 0xc0, 0x4a, 0x31,
	0xa4, 0x09, 0xb3, 0x5e, 0x1b, 0xc6, 0xed, 0x15, 0x9c, 0x63, 0x1f, 0x7a, 0x85, 0x6f, 0xe8, 0x1e,
	0x34, 0xc2, 0x68, 0x4c, 0xcd, 0x09, 0x14, 0x1a, 0xb8, 0x3f, 0x35, 0xbb, 0xd5, 0x77, 0xf4, 0x10,
	0xda, 0x31, 0x49, 0x68, 0x68, 0xe6, 0xa9, 0xde, 0x34, 0x35, 0xc1, 0xaf, 0xa1, 0x93, 0x2a, 0xe5,
	0x1c, 0xaa, 0x19, 0x55, 0x21, 0x9a, 0xae, 0x16, 0xa4, 0x36, 0x20, 0x23, 0x1a, 0x18, 0xe8, 0x6a,
	0x41, 0x6a, 0x63, 0x22, 0xa6, 0xdc, 0xb1, 0xf5, 0xcc, 0x2a, 0x41, 0xc2, 0x34, 0x88, 0x7c, 0x9e,
	0x1e, 0x8e, 0x5c, 0xe3, 0x9f, 0x2c, 0xe8, 0x64, 0x43, 0xb5, 0x01, 0xad, 0x12, 0x0c, 0x8c, 0x24,
	0xf5, 0xca, 0x6f, 0x8a, 0x01, 0x23, 0xa1, 0x0f, 0x00, 0xce, 0x99, 0xf0, 0xfc, 0x29, 0x61, 0x21,
	0x57, 0xb3, 0xd0, 0x1b, 0x3a, 0xa5, 0xd9, 0xf9, 0x92, 0x89, 0x90, 0x72, 0xfe, 0x2a, 0x1a, 0x53,
	0xb7, 0x7b, 0xce, 0xc4, 0x33, 0x65, 0x2a, 0x47, 0x48, 0xcd, 0x1c, 0x11, 0x53, 0xa7, 0xa1, 0x5c,
	0xb6, 0xe5, 0x78, 0x11, 0x31, 0xc5, 0x23, 0x58, 0x2d, 0xef, 0x93, 0x69, 0xd3, 0x80, 0x9e, 0x18,
	0xb8, 0xab, 0xb5, 0xe4, 0xb0, 0x73, 0x03, 0xf4, 0x15, 0x57, 0x2e, 0xd1, 0x03, 0xcd, 0x6a, 0x97,
	0x25, 0x21, 0x8d, 0xf0, 0x0f, 0x16, 0xdc, 0x49, 0xc9, 0xb1, 0x08, 0xb0, 0x4f, 0x93, 0x8f, 0x69,
	0x40, 0x05, 0x8b, 0x42, 0xdd, 0x8f, 0xc7, 0xd0, 0x53, 0x2c, 0x5e, 0x60, 0xe5, 0x12, 0xbc, 0x0f,
	0x22, 0xc6, 0x0f, 0xd5, 0x37, 0x17, 0xe2, 0x6c, 0x8d, 0xee, 0xc3, 0xff, 0x32, 0x3a, 0xf3, 0xc8,
	0x28, 0x3a, 0xa3, 0x26, 0xd1, 0xd5, 0x4c, 0xbd, 0x2b, 0xb5, 0xf8, 0x05, 0x40, 0xee, 0xa2, 0x86,
	0x97, 0x33, 0xb6, 0x5d, 0xae, 0x63, 0x5b, 0x3b, 0x67, 0x5b, 0xfc, 0xf3, 0x32, 0x5c, 0x37, 0x8c,
	0x71, 0x18, 0x13, 0x9f, 0xaa, 0xfc, 0x75, 0x69, 0x92, 0xe1, 0xb8, 0xd4, 0xc9, 0x73, 0x0a, 0x32,
	0x86, 0x53, 0x2a, 0x49, 0x61, 0xbc, 0x04, 0xe8, 0xe5, 0x39, 0x80, 0xb6, 0xeb, 0x00, 0xdd, 0x28,
	0xdc, 0x0c, 0x26, 0xfb, 0x66, 0x4d, 0xf6, 0xad, 0xba, 0xec, 0xdb, 0x85, 0xbb, 0xe2, 0x01, 0x34,
	0x35, 0xfc, 0x3a, 0xd5, 0x0e, 0xe7, 0xc5, 0xb8, 0xda, 0x04, 0x7d, 0x02, 0x77, 0x74, 0xb2, 0xba,
	0x26, 0xcd, 0x14, 0x53, 0xc2, 0xa7, 0x5e, 0x1c, 0x05, 0xc7, 0x64, 0x1c, 0x09, 0x8f, 0xb3, 0x89,
	0xd3, 0x55, 0x79, 0xdc, 0x56, 0xa6, 0xb9, 0x93, 0x17, 0x84, 0x4f, 0x0f, 0x8c, 0xd9, 0x21, 0x9b,
	0xe0, 0x5f, 0x2c, 0x80, 0xfc, 0xab, 0x02, 0x08, 0x3d, 0x12, 0xea, 0x08, 0x6c, 0x57, 0xad, 0x15,
	0xfd, 0xb3, 0xc9, 0x34, 0x3b, 0x03, 0x25, 0xa0, 0x1d, 0x68, 0xa9, 0xc8, 0x1a, 0x61, 0xbd, 0xe1,
	0xf5, 0x59, 0x14, 0x6b, 0xbe, 0x35, 0x66, 0xf9, 0x2d, 0xd2, 0x28, 0xdc, 0x22, 0x15, 0x00, 0x35,
	0x95, 0xab, 0x7f, 0x02, 0x20, 0x7c, 0x0c, 0xeb, 0x59, 0x41, 0xbb, 0xe1, 0xf8, 0x25, 0x3d, 0x12,
	0xae, 0x4a, 0x6c, 0x00, 0x6b, 0xd5, 0xc6, 0x98, 0x89, 0x5a, 0xe5, 0xa5, 0x36, 0x64, 0xc5, 0x2e,
	0xd7, 0x15, 0x6b, 0x17, 0x8a, 0xc5, 0x1f, 0xc2, 0x95, 0x52, 0x51, 0xe8, 0x41, 0x56, 0xbd, 0x35,
	0x97, 0xc3, 0x8c, 0x05, 0x7e, 0x02, 0x4e, 0x0a, 0xb5, 0x99, 0xc9, 0x2c, 0x3d, 0x04, 0xac, 0xea,
	0x43, 0xe0, 0x77, 0x0b, 0x6e, 0xce, 0x99, 0xe9, 0xcf, 0x23, 0x41, 0x16, 0xbe, 0x05, 0x1e, 0x01,
	0xe8, 0x06, 0x04, 0x8c, 0x0b, 0xc3, 0xb4, 0x05, 0x56, 0x7f, 0x1a, 0x44, 0xfe, 0x31, 0xd7, 0x89,
	0x76, 0x95, 0xe1, 0x4b, 0xc6, 0x45, 0x3e, 0xb1, 0x76, 0xdd, 0xc4, 0x36, 0x0a, 0x13, 0x3b, 0x3b,
	0xed, 0x15, 0x94, 0xb5, 0xaa, 0x28, 0xc3, 0x3f, 0x5a, 0xd0, 0x2b, 0xc4, 0x45, 0x5f, 0xc3, 0x8d,
	0xc2, 0xf0, 0x92, 0x70, 0xec, 0xc9, 0x23, 0xf0, 0x74, 0xff, 0x35, 0xd5, 0x14, 0xae, 0xbb, 0xda,
	0xd3, 0x76, 0xd7, 0xe3, 0xda, 0x21, 0x28, 0xf5, 0xd5, 0xae, 0xf6, 0xf5, 0x0f, 0x0b, 0x1e, 0xce,
	0x3b, 0x12, 0xd5, 0xd8, 0xc3, 0xd4, 0x74, 0x9f, 0x9e, 0x8c, 0x68, 0xb2, 0xa8, 0xcf, 0x03, 0x58,
	0x13, 0x72, 0x4b, 0x71, 0xdc, 0x0c, 0xd7, 0x29, 0x7d, 0x3e, 0x6e, 0xff, 0x69, 0x6f, 0x2f, 0xe0,
	0xd6, 0xc2, 0x8a, 0x16, 0x95, 0xb0, 0x09, 0x3d, 0x36, 0x0e, 0xa8, 0x97, 0x50, 0x7e, 0x1a, 0x68,
	0x38, 0x74, 0x5c, 0x90, 0x2a, 0x57, 0x69, 0x2e, 0xe9, 0xe6, 0x6f, 0x56, 0xf6, 0x5e, 0xd5, 0x01,
	0xcb, 0x57, 0x48, 0x86, 0x7b, 0xab, 0x88, 0xfb, 0xc7, 0xd0, 0xcd, 0x70, 0x6f, 0xde, 0x5c, 0xf3,
	0x61, 0xdf, 0x49, 0x61, 0x5f, 0xba, 0x36, 0xed, 0xd2, 0xb5, 0x59, 0x2a, 0xb0, 0x31, 0x87, 0xc3,
	0x9b, 0x75, 0x1c, 0xde, 0xca, 0x39, 0x7c, 0xf8, 0x57, 0x13, 0xda, 0xf2, 0x42, 0xda, 0x8d, 0x19,
	0x7a, 0x0d, 0x37, 0x12, 0x5d, 0x96, 0xa7, 0x1d, 0x4f, 0xa8, 0xf0, 0x42, 0x7a, 0xee, 0x1d, 0xd3,
	0x0b, 0x54, 0x18, 0xcc, 0xda, 0x3f, 0x93, 0xfe, 0x56, 0xd1, 0xa0, 0xee, 0x2f, 0x04, 0x2f, 0xa1,
	0x6f, 0x61, 0xa3, 0x1c, 0x21, 0x49, 0x7f, 0x84, 0x2e, 0x75, 0xbf, 0x39, 0xc7, 0x7d, 0xfa, 0x2b,
	0x85, 0x97, 0xd0, 0x77, 0x70, 0xbb, 0xec, 0xdd, 0xbc, 0xf3, 0x26, 0x34, 0x54, 0x63, 0x14, 0xa0,
	0xbb, 0xf5, 0x51, 0xca, 0x3f, 0x1c, 0xfd, 0xab, 0x85, 0xb7, 0x60, 0xfa, 0xe0, 0xc7, 0x4b, 0xe8,
	0x0d, 0xbc, 0x95, 0xba, 0x3f, 0x53, 0xc7, 0xee, 0x15, 0xdf, 0x91, 0x68, 0x30, 0xe3, 0x7b, 0xce,
	0x43, 0xbe, 0xff, 0xee, 0x6c, 0x29, 0x0b, 0x9e, 0x24, 0x78, 0x09, 0x25, 0x70, 0x3f, 0x8d, 0x5c,
	0x64, 0x7a, 0x93, 0x05, 0x67, 0xe1, 0x24, 0xa0, 0xde, 0x48, 0x12, 0x0d, 0x7a, 0x7b, 0x26, 0x8b,
	0x2a, 0x3a, 0xfa, 0x78, 0x36, 0x7c, 0xd5, 0x06, 0x2f, 0xa1, 0x08, 0xfa, 0x95, 0x6a, 0x75, 0x68,
	0x85, 0x71, 0x74, 0xef, 0xd2, 0x30, 0x0a, 0x84, 0xfd, 0xfb, 0x97, 0xc7, 0x52, 0x86, 0x78, 0x09,
	0x9d, 0xc1, 0xad, 0x4a, 0xc0, 0xb1, 0x69, 0x83, 0x69, 0xf0, 0xdd, 0x39, 0x0d, 0x2e, 0x75, 0xeb,
	0x5f, 0x37, 0xf7, 0xe9, 0x95, 0x6f, 0x7a, 0xdb, 0xdb, 0x3b, 0xea, 0xd1, 0x97, 0xc4, 0xfe, 0xa8,
	0xa5, 0xfe, 0xdd, 0xdf, 0xfb, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xe0, 0x6e, 0x9b, 0xcd, 0x0f,
	0x00, 0x00,
}
